/*
 * JSP generated by Resin-3.1.9 (built Mon, 13 Apr 2009 11:09:12 PDT)
 */

package _jsp._pages;
import javax.servlet.*;
import javax.servlet.jsp.*;
import javax.servlet.http.*;

public class _header__jsp extends com.caucho.jsp.JavaPage
{
  private static final java.util.HashMap<String,java.lang.reflect.Method> _jsp_functionMap = new java.util.HashMap<String,java.lang.reflect.Method>();
  private boolean _caucho_isDead;
  
  public void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response)
    throws java.io.IOException, javax.servlet.ServletException
  {
    javax.servlet.http.HttpSession session = request.getSession(true);
    com.caucho.server.webapp.WebApp _jsp_application = _caucho_getApplication();
    javax.servlet.ServletContext application = _jsp_application;
    com.caucho.jsp.PageContextImpl pageContext = _jsp_application.getJspApplicationContext().allocatePageContext(this, _jsp_application, request, response, null, session, 8192, true, false);
    javax.servlet.jsp.PageContext _jsp_parentContext = pageContext;
    javax.servlet.jsp.JspWriter out = pageContext.getOut();
    final javax.el.ELContext _jsp_env = pageContext.getELContext();
    javax.servlet.ServletConfig config = getServletConfig();
    javax.servlet.Servlet page = this;
    response.setContentType("text/html;charset=UTF-8");
    request.setCharacterEncoding("UTF-8");
    try {
      out.write(_jsp_string0, 0, _jsp_string0.length);
      _caucho_expr_0.print(out, _jsp_env, false);
      out.write(_jsp_string1, 0, _jsp_string1.length);
      _caucho_expr_1.print(out, _jsp_env, false);
      out.write(_jsp_string2, 0, _jsp_string2.length);
      _caucho_expr_2.print(out, _jsp_env, false);
      out.write(_jsp_string3, 0, _jsp_string3.length);
    } catch (java.lang.Throwable _jsp_e) {
      pageContext.handlePageException(_jsp_e);
    } finally {
      _jsp_application.getJspApplicationContext().freePageContext(pageContext);
    }
  }

  private java.util.ArrayList _caucho_depends = new java.util.ArrayList();

  public java.util.ArrayList _caucho_getDependList()
  {
    return _caucho_depends;
  }

  public void _caucho_addDepend(com.caucho.vfs.PersistentDependency depend)
  {
    super._caucho_addDepend(depend);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
  }

  public boolean _caucho_isModified()
  {
    if (_caucho_isDead)
      return true;
    if (com.caucho.server.util.CauchoSystem.getVersionId() != 5783496155892875126L)
      return true;
    for (int i = _caucho_depends.size() - 1; i >= 0; i--) {
      com.caucho.vfs.Dependency depend;
      depend = (com.caucho.vfs.Dependency) _caucho_depends.get(i);
      if (depend.isModified())
        return true;
    }
    return false;
  }

  public long _caucho_lastModified()
  {
    return 0;
  }

  public java.util.HashMap<String,java.lang.reflect.Method> _caucho_getFunctionMap()
  {
    return _jsp_functionMap;
  }

  public void init(ServletConfig config)
    throws ServletException
  {
    com.caucho.server.webapp.WebApp webApp
      = (com.caucho.server.webapp.WebApp) config.getServletContext();
    super.init(config);
    com.caucho.jsp.TaglibManager manager = webApp.getJspApplicationContext().getTaglibManager();
    com.caucho.jsp.PageContextImpl pageContext = new com.caucho.jsp.PageContextImpl(webApp, this);
    _caucho_expr_0 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${sessionScope.userLogin.userName}");
    _caucho_expr_1 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${sessionScope.userLogin.fullNameRole}");
    _caucho_expr_2 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${sessionScope.userLogin.sfi.abbreviationEn}");
  }

  public void destroy()
  {
      _caucho_isDead = true;
      super.destroy();
  }

  public void init(com.caucho.vfs.Path appDir)
    throws javax.servlet.ServletException
  {
    com.caucho.vfs.Path resinHome = com.caucho.server.util.CauchoSystem.getResinHome();
    com.caucho.vfs.MergePath mergePath = new com.caucho.vfs.MergePath();
    mergePath.addMergePath(appDir);
    mergePath.addMergePath(resinHome);
    com.caucho.loader.DynamicClassLoader loader;
    loader = (com.caucho.loader.DynamicClassLoader) getClass().getClassLoader();
    String resourcePath = loader.getResourcePathSpecificFirst();
    mergePath.addClassPath(resourcePath);
    com.caucho.vfs.Depend depend;
    depend = new com.caucho.vfs.Depend(appDir.lookup("pages/header.jsp"), 2271829195600460894L, false);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
  }
  private static com.caucho.el.Expr _caucho_expr_0;
  private static com.caucho.el.Expr _caucho_expr_1;
  private static com.caucho.el.Expr _caucho_expr_2;

  private final static char []_jsp_string1;
  private final static char []_jsp_string3;
  private final static char []_jsp_string2;
  private final static char []_jsp_string0;
  static {
    _jsp_string1 = " (".toCharArray();
    _jsp_string3 = " </span>\n                        <font face=\"Arial Narrow\" color=\"orange\" onclick=\"logout();\"\n                              onmouseover=\"this.style.cursor='hand'; style.color='#A5FFA7';\"\n                              onmouseout=\"style.color='orange'\"\n                              style=\"padding-right:5px; padding-left:15px; font-size:12px; cursor:pointer;\">Log\n                            out</font>\n                    </b>\n                </td>\n                </tr>\n            </table>\n        </td>\n    </tr>\n</table>\n \n\n \n        \n            \n                \n                \n                    \n                        \n                    \n                    \n                        \n                    \n                \n            \n        \n    \n    \n        \n            \n                \n                    \n                        \n                    \n                        \n                            \n                            \n                            \n                                  \n                                  \n                                  \n                        \n                    \n                \n            \n        \n    \n\n\n\n\n".toCharArray();
    _jsp_string2 = "), ".toCharArray();
    _jsp_string0 = "\n\n<script type=\"text/javascript\">\n        function logout() {\n            if (confirm(\"Are you sure you want to log out?\")) {\n                parent.bodyFrame.location = '../account/logout.action';\n            }\n        }\n    </script>\n<style type=\"text/css\">\n    html, body {\n        font-size: 11px;\n        font-family: \"Ms Sans Serif\";\n        margin: 0;\n        padding: 0;\n        border: none;\n    }\n\n   table,tr, td {\n        margin: 0px;\n        padding: 0px\n    }\n</style>\n<table style=\"width:100%;height:100%;\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"background:#ccffff\">\n    <tr>\n        <td>\n            <table style=\"width:100%;height:100%;\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"margin-top:0;padding:0;\">\n                \n                <tr style=\"background-image:url(../images/head/bg_head_m.gif);\">\n                    <td align=\"left\" width=\"267px\"><img src=\"../images/head/logo-header.png\" style=\"padding:0;margin:0;\"/></td>\n                    <td style=\"background-image:url(../images/head/bg_head_m.gif);\"></td>\n                    <td align=\"right\" width=\"737px\" style=\"padding-right:20px;\">\n                        <img src=\"../images/head/text_header.png\" style=\"border:0px;padding:0;margin:0;\"/>\n                    </td>\n                </tr>\n                <tr>\n                    \n                    <td style=\"height:20px;\" width=\"250px\" bgcolor=\"#add8e6\"/>\n                    \n                    <td colspan=\"2\" style=\"height:20px;\" align=\"right\" bgcolor=\"#add8e6\">\n\n                    <b>\n                        \n                        <span style=\"color:#FFFFFF; font-family:Verdana; color:orangered; font-size:12px;\">Welcome </span>\n                        <span style=\"color:#FFFFFF; font-family:Verdana; color:darkblue; font-size:12px;\">".toCharArray();
  }
}
