/*
 * JSP generated by Resin-3.1.9 (built Mon, 13 Apr 2009 11:09:12 PDT)
 */

package _jsp._pages;
import javax.servlet.*;
import javax.servlet.jsp.*;
import javax.servlet.http.*;

public class _menu__jsp extends com.caucho.jsp.JavaPage
{
  private static final java.util.HashMap<String,java.lang.reflect.Method> _jsp_functionMap = new java.util.HashMap<String,java.lang.reflect.Method>();
  private boolean _caucho_isDead;
  
  public void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response)
    throws java.io.IOException, javax.servlet.ServletException
  {
    javax.servlet.http.HttpSession session = request.getSession(true);
    com.caucho.server.webapp.WebApp _jsp_application = _caucho_getApplication();
    javax.servlet.ServletContext application = _jsp_application;
    com.caucho.jsp.PageContextImpl pageContext = _jsp_application.getJspApplicationContext().allocatePageContext(this, _jsp_application, request, response, null, session, 8192, true, false);
    javax.servlet.jsp.PageContext _jsp_parentContext = pageContext;
    javax.servlet.jsp.JspWriter out = pageContext.getOut();
    final javax.el.ELContext _jsp_env = pageContext.getELContext();
    javax.servlet.ServletConfig config = getServletConfig();
    javax.servlet.Servlet page = this;
    response.setContentType("text/html;charset=UTF-8");
    request.setCharacterEncoding("UTF-8");
    try {
      out.write(_jsp_string0, 0, _jsp_string0.length);
      if (_caucho_expr_0.evalBoolean(_jsp_env)) {
        out.write(_jsp_string1, 0, _jsp_string1.length);
      }
      out.write(_jsp_string2, 0, _jsp_string2.length);
      if (_caucho_expr_1.evalBoolean(_jsp_env)) {
        out.write(_jsp_string3, 0, _jsp_string3.length);
      }
      out.write(_jsp_string2, 0, _jsp_string2.length);
      if (_caucho_expr_2.evalBoolean(_jsp_env)) {
        out.write(_jsp_string4, 0, _jsp_string4.length);
        if (_caucho_expr_3.evalBoolean(_jsp_env)) {
          out.write(_jsp_string5, 0, _jsp_string5.length);
        }
        out.write(_jsp_string6, 0, _jsp_string6.length);
        if (_caucho_expr_4.evalBoolean(_jsp_env)) {
          out.write(_jsp_string7, 0, _jsp_string7.length);
        }
        out.write(_jsp_string8, 0, _jsp_string8.length);
      }
      out.write(_jsp_string2, 0, _jsp_string2.length);
      if (_caucho_expr_5.evalBoolean(_jsp_env)) {
        out.write(_jsp_string9, 0, _jsp_string9.length);
        if (_caucho_expr_6.evalBoolean(_jsp_env)) {
          out.write(_jsp_string10, 0, _jsp_string10.length);
          if (_caucho_expr_7.evalBoolean(_jsp_env)) {
            out.write(_jsp_string11, 0, _jsp_string11.length);
            if (_caucho_expr_8.evalBoolean(_jsp_env)) {
              out.write(_jsp_string12, 0, _jsp_string12.length);
            }
            out.write(_jsp_string11, 0, _jsp_string11.length);
            if (_caucho_expr_9.evalBoolean(_jsp_env)) {
              out.write(_jsp_string13, 0, _jsp_string13.length);
            }
            out.write(_jsp_string11, 0, _jsp_string11.length);
            if (_caucho_expr_10.evalBoolean(_jsp_env)) {
              out.write(_jsp_string14, 0, _jsp_string14.length);
            }
            out.write(_jsp_string11, 0, _jsp_string11.length);
            if (_caucho_expr_11.evalBoolean(_jsp_env)) {
              out.write(_jsp_string15, 0, _jsp_string15.length);
            }
            out.write(_jsp_string11, 0, _jsp_string11.length);
            if (_caucho_expr_12.evalBoolean(_jsp_env)) {
              out.write(_jsp_string16, 0, _jsp_string16.length);
            }
            out.write(_jsp_string17, 0, _jsp_string17.length);
          }
          out.write(_jsp_string18, 0, _jsp_string18.length);
        }
        out.write(_jsp_string19, 0, _jsp_string19.length);
        if (_caucho_expr_13.evalBoolean(_jsp_env)) {
          out.write(_jsp_string20, 0, _jsp_string20.length);
        }
        out.write(_jsp_string21, 0, _jsp_string21.length);
        if (_caucho_expr_14.evalBoolean(_jsp_env)) {
          out.write(_jsp_string22, 0, _jsp_string22.length);
        }
        out.write(_jsp_string23, 0, _jsp_string23.length);
      }
      out.write(_jsp_string24, 0, _jsp_string24.length);
      if (_caucho_expr_15.evalBoolean(_jsp_env)) {
        out.write(_jsp_string25, 0, _jsp_string25.length);
        if (_caucho_expr_16.evalBoolean(_jsp_env)) {
          out.write(_jsp_string26, 0, _jsp_string26.length);
        }
        out.write(_jsp_string17, 0, _jsp_string17.length);
        if (_caucho_expr_17.evalBoolean(_jsp_env)) {
          out.write(_jsp_string27, 0, _jsp_string27.length);
        }
        out.write(_jsp_string17, 0, _jsp_string17.length);
        if (_caucho_expr_18.evalBoolean(_jsp_env)) {
          out.write(_jsp_string28, 0, _jsp_string28.length);
        }
        out.write(_jsp_string17, 0, _jsp_string17.length);
        if (_caucho_expr_19.evalBoolean(_jsp_env)) {
          out.write(_jsp_string29, 0, _jsp_string29.length);
        }
        out.write(_jsp_string30, 0, _jsp_string30.length);
      }
      out.write(_jsp_string24, 0, _jsp_string24.length);
      if (_caucho_expr_20.evalBoolean(_jsp_env)) {
        out.write(_jsp_string31, 0, _jsp_string31.length);
        if (_caucho_expr_21.evalBoolean(_jsp_env)) {
          out.write(_jsp_string32, 0, _jsp_string32.length);
        }
        out.write(_jsp_string17, 0, _jsp_string17.length);
        if (_caucho_expr_22.evalBoolean(_jsp_env)) {
          out.write(_jsp_string33, 0, _jsp_string33.length);
        }
        out.write(_jsp_string34, 0, _jsp_string34.length);
      }
      out.write(_jsp_string2, 0, _jsp_string2.length);
      if (_caucho_expr_23.evalBoolean(_jsp_env)) {
        out.write(_jsp_string35, 0, _jsp_string35.length);
        if (_caucho_expr_24.evalBoolean(_jsp_env)) {
          out.write(_jsp_string36, 0, _jsp_string36.length);
        }
        out.write(_jsp_string37, 0, _jsp_string37.length);
        if (_caucho_expr_25.evalBoolean(_jsp_env)) {
          out.write(_jsp_string38, 0, _jsp_string38.length);
        }
        out.write(_jsp_string37, 0, _jsp_string37.length);
        if (_caucho_expr_26.evalBoolean(_jsp_env)) {
          out.write(_jsp_string39, 0, _jsp_string39.length);
        }
        out.write(_jsp_string40, 0, _jsp_string40.length);
      }
      out.write(_jsp_string41, 0, _jsp_string41.length);
      if (_caucho_expr_27.evalBoolean(_jsp_env)) {
        out.write(_jsp_string42, 0, _jsp_string42.length);
        if (_caucho_expr_28.evalBoolean(_jsp_env)) {
          out.write(_jsp_string43, 0, _jsp_string43.length);
        }
        out.write(_jsp_string17, 0, _jsp_string17.length);
        if (_caucho_expr_29.evalBoolean(_jsp_env)) {
          out.write(_jsp_string44, 0, _jsp_string44.length);
        }
        out.write(_jsp_string45, 0, _jsp_string45.length);
      }
      out.write(_jsp_string46, 0, _jsp_string46.length);
      if (_caucho_expr_30.evalBoolean(_jsp_env)) {
        out.write(_jsp_string47, 0, _jsp_string47.length);
        if (_caucho_expr_31.evalBoolean(_jsp_env)) {
          out.write(_jsp_string48, 0, _jsp_string48.length);
        }
        out.write(_jsp_string17, 0, _jsp_string17.length);
        if (_caucho_expr_32.evalBoolean(_jsp_env)) {
          out.write(_jsp_string49, 0, _jsp_string49.length);
        }
        out.write(_jsp_string50, 0, _jsp_string50.length);
        if (_caucho_expr_33.evalBoolean(_jsp_env)) {
          out.write(_jsp_string51, 0, _jsp_string51.length);
        }
        out.write(_jsp_string50, 0, _jsp_string50.length);
        if (_caucho_expr_34.evalBoolean(_jsp_env)) {
          out.write(_jsp_string52, 0, _jsp_string52.length);
        }
        out.write(_jsp_string50, 0, _jsp_string50.length);
        if (_caucho_expr_35.evalBoolean(_jsp_env)) {
          out.write(_jsp_string53, 0, _jsp_string53.length);
        }
        out.write(_jsp_string8, 0, _jsp_string8.length);
      }
      out.write(_jsp_string2, 0, _jsp_string2.length);
      if (_caucho_expr_36.evalBoolean(_jsp_env)) {
        out.write(_jsp_string54, 0, _jsp_string54.length);
        if (_caucho_expr_37.evalBoolean(_jsp_env)) {
          out.write(_jsp_string55, 0, _jsp_string55.length);
        }
        out.write(_jsp_string17, 0, _jsp_string17.length);
        if (_caucho_expr_38.evalBoolean(_jsp_env)) {
          out.write(_jsp_string56, 0, _jsp_string56.length);
        }
        out.write(_jsp_string17, 0, _jsp_string17.length);
        if (_caucho_expr_39.evalBoolean(_jsp_env)) {
          out.write(_jsp_string57, 0, _jsp_string57.length);
        }
        out.write(_jsp_string58, 0, _jsp_string58.length);
        if (_caucho_expr_40.evalBoolean(_jsp_env)) {
          out.write(_jsp_string59, 0, _jsp_string59.length);
        }
        out.write(_jsp_string17, 0, _jsp_string17.length);
        if (_caucho_expr_41.evalBoolean(_jsp_env)) {
          out.write(_jsp_string60, 0, _jsp_string60.length);
        }
        out.write(_jsp_string61, 0, _jsp_string61.length);
        if (_caucho_expr_42.evalBoolean(_jsp_env)) {
          out.write(_jsp_string62, 0, _jsp_string62.length);
        }
        out.write(_jsp_string17, 0, _jsp_string17.length);
        if (_caucho_expr_43.evalBoolean(_jsp_env)) {
          out.write(_jsp_string63, 0, _jsp_string63.length);
        }
        out.write(_jsp_string17, 0, _jsp_string17.length);
        if (_caucho_expr_44.evalBoolean(_jsp_env)) {
          out.write(_jsp_string64, 0, _jsp_string64.length);
        }
        out.write(_jsp_string17, 0, _jsp_string17.length);
        if (_caucho_expr_45.evalBoolean(_jsp_env)) {
          out.write(_jsp_string65, 0, _jsp_string65.length);
        }
        out.write(_jsp_string30, 0, _jsp_string30.length);
      }
      out.write(_jsp_string2, 0, _jsp_string2.length);
      if (_caucho_expr_46.evalBoolean(_jsp_env)) {
        out.write(_jsp_string66, 0, _jsp_string66.length);
        if (_caucho_expr_47.evalBoolean(_jsp_env)) {
          out.write(_jsp_string67, 0, _jsp_string67.length);
        }
        out.write(_jsp_string68, 0, _jsp_string68.length);
        if (_caucho_expr_48.evalBoolean(_jsp_env)) {
          out.write(_jsp_string69, 0, _jsp_string69.length);
        }
        out.write(_jsp_string70, 0, _jsp_string70.length);
        if (_caucho_expr_49.evalBoolean(_jsp_env)) {
          out.write(_jsp_string71, 0, _jsp_string71.length);
        }
        out.write(_jsp_string70, 0, _jsp_string70.length);
        if (_caucho_expr_50.evalBoolean(_jsp_env)) {
          out.write(_jsp_string72, 0, _jsp_string72.length);
        }
        out.write(_jsp_string73, 0, _jsp_string73.length);
      }
      out.write(_jsp_string2, 0, _jsp_string2.length);
      if (_caucho_expr_51.evalBoolean(_jsp_env)) {
        out.write(_jsp_string74, 0, _jsp_string74.length);
        if (_caucho_expr_52.evalBoolean(_jsp_env)) {
          out.write(_jsp_string75, 0, _jsp_string75.length);
        }
        out.write(_jsp_string68, 0, _jsp_string68.length);
        if (_caucho_expr_53.evalBoolean(_jsp_env)) {
          out.write(_jsp_string76, 0, _jsp_string76.length);
        }
        out.write(_jsp_string68, 0, _jsp_string68.length);
        if (_caucho_expr_54.evalBoolean(_jsp_env)) {
          out.write(_jsp_string77, 0, _jsp_string77.length);
        }
        out.write(_jsp_string68, 0, _jsp_string68.length);
        if (_caucho_expr_55.evalBoolean(_jsp_env)) {
          out.write(_jsp_string78, 0, _jsp_string78.length);
        }
        out.write(_jsp_string68, 0, _jsp_string68.length);
        if (_caucho_expr_56.evalBoolean(_jsp_env)) {
          out.write(_jsp_string79, 0, _jsp_string79.length);
        }
        out.write(_jsp_string68, 0, _jsp_string68.length);
        if (_caucho_expr_57.evalBoolean(_jsp_env)) {
          out.write(_jsp_string80, 0, _jsp_string80.length);
        }
        out.write(_jsp_string68, 0, _jsp_string68.length);
        if (_caucho_expr_58.evalBoolean(_jsp_env)) {
          out.write(_jsp_string81, 0, _jsp_string81.length);
        }
        out.write(_jsp_string82, 0, _jsp_string82.length);
      }
      out.write(_jsp_string2, 0, _jsp_string2.length);
      if (_caucho_expr_59.evalBoolean(_jsp_env)) {
        out.write(_jsp_string83, 0, _jsp_string83.length);
      }
      out.write(_jsp_string84, 0, _jsp_string84.length);
      if (_caucho_expr_60.evalBoolean(_jsp_env)) {
        out.write(_jsp_string85, 0, _jsp_string85.length);
        if (_caucho_expr_61.evalBoolean(_jsp_env)) {
          out.write(_jsp_string86, 0, _jsp_string86.length);
        }
        out.write(_jsp_string87, 0, _jsp_string87.length);
        if (_caucho_expr_62.evalBoolean(_jsp_env)) {
          out.write(_jsp_string88, 0, _jsp_string88.length);
          if (_caucho_expr_63.evalBoolean(_jsp_env)) {
            out.write(_jsp_string89, 0, _jsp_string89.length);
          }
          out.write(_jsp_string90, 0, _jsp_string90.length);
          if (_caucho_expr_64.evalBoolean(_jsp_env)) {
            out.write(_jsp_string91, 0, _jsp_string91.length);
          }
          out.write(_jsp_string90, 0, _jsp_string90.length);
          if (_caucho_expr_65.evalBoolean(_jsp_env)) {
            out.write(_jsp_string92, 0, _jsp_string92.length);
          }
          out.write(_jsp_string93, 0, _jsp_string93.length);
        }
        out.write(_jsp_string94, 0, _jsp_string94.length);
      }
      out.write(_jsp_string95, 0, _jsp_string95.length);
    } catch (java.lang.Throwable _jsp_e) {
      pageContext.handlePageException(_jsp_e);
    } finally {
      _jsp_application.getJspApplicationContext().freePageContext(pageContext);
    }
  }

  private java.util.ArrayList _caucho_depends = new java.util.ArrayList();

  public java.util.ArrayList _caucho_getDependList()
  {
    return _caucho_depends;
  }

  public void _caucho_addDepend(com.caucho.vfs.PersistentDependency depend)
  {
    super._caucho_addDepend(depend);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
  }

  public boolean _caucho_isModified()
  {
    if (_caucho_isDead)
      return true;
    if (com.caucho.server.util.CauchoSystem.getVersionId() != 5783496155892875126L)
      return true;
    for (int i = _caucho_depends.size() - 1; i >= 0; i--) {
      com.caucho.vfs.Dependency depend;
      depend = (com.caucho.vfs.Dependency) _caucho_depends.get(i);
      if (depend.isModified())
        return true;
    }
    return false;
  }

  public long _caucho_lastModified()
  {
    return 0;
  }

  public java.util.HashMap<String,java.lang.reflect.Method> _caucho_getFunctionMap()
  {
    return _jsp_functionMap;
  }

  public void init(ServletConfig config)
    throws ServletException
  {
    com.caucho.server.webapp.WebApp webApp
      = (com.caucho.server.webapp.WebApp) config.getServletContext();
    super.init(config);
    com.caucho.jsp.TaglibManager manager = webApp.getJspApplicationContext().getTaglibManager();
    manager.addTaglibFunctions(_jsp_functionMap, "c", "http://java.sun.com/jstl/core_rt");
    manager.addTaglibFunctions(_jsp_functionMap, "fmt", "http://java.sun.com/jstl/fmt");
    com.caucho.jsp.PageContextImpl pageContext = new com.caucho.jsp.PageContextImpl(webApp, this);
    _caucho_expr_0 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${sessionScope.menuAuthentication.newsInformationView}");
    _caucho_expr_1 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${sessionScope.menuAuthentication.userManagementView}");
    _caucho_expr_2 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${sessionScope.menuAuthentication.sfiManagementView || sessionScope.menuAuthentication.branchCodeView}");
    _caucho_expr_3 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${sessionScope.menuAuthentication.sfiManagementView}");
    _caucho_expr_4 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${sessionScope.menuAuthentication.branchCodeView}");
    _caucho_expr_5 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${sessionScope.menuAuthentication.structuredDatasetView || sessionScope.menuAuthentication.unstructuredDatasetView  }");
    _caucho_expr_6 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${sessionScope.menuAuthentication.structuredDatasetView}");
    _caucho_expr_7 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${sessionScope.menuAuthentication.classificationView || sessionScope.menuAuthentication.isicCodeView || sessionScope.menuAuthentication.governmentAgencyCodeView || sessionScope.menuAuthentication.reportTypeView || sessionScope.menuAuthentication.rulesValidationView}");
    _caucho_expr_8 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${sessionScope.menuAuthentication.classificationView}");
    _caucho_expr_9 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${sessionScope.menuAuthentication.isicCodeView}");
    _caucho_expr_10 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${sessionScope.menuAuthentication.governmentAgencyCodeView}");
    _caucho_expr_11 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${sessionScope.menuAuthentication.reportTypeView}");
    _caucho_expr_12 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${sessionScope.menuAuthentication.rulesValidationView}");
    _caucho_expr_13 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${sessionScope.menuAuthentication.unstructuredDatasetView}");
    _caucho_expr_14 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${sessionScope.menuAuthentication.moveUnStructuredManage}");
    _caucho_expr_15 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${sessionScope.menuAuthentication.submitStructuredView || sessionScope.menuAuthentication.viewSubmittedStructuredView || sessionScope.menuAuthentication.submitAdjustView || sessionScope.menuAuthentication.viewSumbittedAdjustView}");
    _caucho_expr_16 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${sessionScope.menuAuthentication.submitStructuredView}");
    _caucho_expr_17 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${sessionScope.menuAuthentication.viewSubmittedStructuredView}");
    _caucho_expr_18 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${sessionScope.menuAuthentication.submitAdjustView}");
    _caucho_expr_19 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${sessionScope.menuAuthentication.viewSumbittedAdjustView}");
    _caucho_expr_20 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${sessionScope.menuAuthentication.submitUnstructuredView || sessionScope.menuAuthentication.viewSubmittedUnstructuredView}");
    _caucho_expr_21 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${sessionScope.menuAuthentication.submitUnstructuredView}");
    _caucho_expr_22 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${sessionScope.menuAuthentication.viewSubmittedUnstructuredView}");
    _caucho_expr_23 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${sessionScope.menuAuthentication.submitPublishDocumentView || sessionScope.menuAuthentication.viewPublishDocumentView || sessionScope.menuAuthentication.viewPublishView}");
    _caucho_expr_24 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${sessionScope.menuAuthentication.viewPublishView}");
    _caucho_expr_25 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${sessionScope.menuAuthentication.submitPublishDocumentView}");
    _caucho_expr_26 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${sessionScope.menuAuthentication.viewPublishDocumentView}");
    _caucho_expr_27 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${sessionScope.menuAuthentication.uploadCSVFileFroBIView || sessionScope.menuAuthentication.compositeRatingAndInputView}");
    _caucho_expr_28 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${sessionScope.menuAuthentication.uploadCSVFileFroBIView}");
    _caucho_expr_29 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${sessionScope.menuAuthentication.compositeRatingAndInputView}");
    _caucho_expr_30 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${sessionScope.menuAuthentication.structuredTransferView || sessionScope.menuAuthentication.adjustStructuredTransferView || sessionScope.menuAuthentication.activityView || sessionScope.menuAuthentication.documentStatusView || sessionScope.menuAuthentication.documentStatusUnstructuredView}");
    _caucho_expr_31 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${sessionScope.menuAuthentication.structuredTransferView}");
    _caucho_expr_32 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${sessionScope.menuAuthentication.adjustStructuredTransferView}");
    _caucho_expr_33 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${sessionScope.menuAuthentication.activityView}");
    _caucho_expr_34 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${sessionScope.menuAuthentication.documentStatusView}");
    _caucho_expr_35 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${sessionScope.menuAuthentication.documentStatusUnstructuredView}");
    _caucho_expr_36 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${sessionScope.menuAuthentication.executiveReportView || sessionScope.menuAuthentication.kpiReportStructuredView || sessionScope.menuAuthentication.kpiReportUnstructuredView || sessionScope.menuAuthentication.monitoringSubmitDatasetView || sessionScope.menuAuthentication.monitoringUnstructuredView || sessionScope.menuAuthentication.kpiReportUnstructuredView || sessionScope.menuAuthentication.kpiReportStructuredBySearchView}");
    _caucho_expr_37 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${sessionScope.menuAuthentication.executiveReportView}");
    _caucho_expr_38 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${sessionScope.menuAuthentication.kpiReportStructuredView}");
    _caucho_expr_39 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${sessionScope.menuAuthentication.kpiReportStructuredBySearchView}");
    _caucho_expr_40 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${sessionScope.menuAuthentication.kpiReportStructuredBOTView}");
    _caucho_expr_41 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${sessionScope.menuAuthentication.kpiReportStructuredBySearchBOTView}");
    _caucho_expr_42 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${sessionScope.menuAuthentication.kpiReportUnstructuredView}");
    _caucho_expr_43 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${sessionScope.menuAuthentication.monitoringSubmitDatasetView}");
    _caucho_expr_44 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${sessionScope.menuAuthentication.monitoringUnstructuredView}");
    _caucho_expr_45 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${sessionScope.menuAuthentication.exportLogReportView}");
    _caucho_expr_46 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${sessionScope.menuAuthentication.definedDataView || sessionScope.menuAuthentication.exportDataView || sessionScope.menuAuthentication.definedDataUnstructuredView || sessionScope.menuAuthentication.exportDataUnstructuredView}");
    _caucho_expr_47 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${sessionScope.menuAuthentication.definedDataView}");
    _caucho_expr_48 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${sessionScope.menuAuthentication.exportDataView}");
    _caucho_expr_49 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${sessionScope.menuAuthentication.definedDataUnstructuredView}");
    _caucho_expr_50 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${sessionScope.menuAuthentication.exportDataUnstructuredView}");
    _caucho_expr_51 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${sessionScope.menuAuthentication.systemView || sessionScope.menuAuthentication.frequencyView || sessionScope.menuAuthentication.sendingWaiveView || sessionScope.menuAuthentication.frequencyUnstructuredView || sessionScope.menuAuthentication.sendingWaiveUnstructuredView}");
    _caucho_expr_52 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${sessionScope.menuAuthentication.systemView}");
    _caucho_expr_53 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${sessionScope.menuAuthentication.frequencyView}");
    _caucho_expr_54 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${sessionScope.menuAuthentication.frequencyUnstructuredView}");
    _caucho_expr_55 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${sessionScope.menuAuthentication.sendingWaiveView}");
    _caucho_expr_56 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${sessionScope.menuAuthentication.sendingWaiveUnstructuredView}");
    _caucho_expr_57 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${sessionScope.menuAuthentication.officialHolidayView}");
    _caucho_expr_58 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${sessionScope.menuAuthentication.noTransactionView}");
    _caucho_expr_59 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${sessionScope.menuAuthentication.defectLogView}");
    _caucho_expr_60 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${sessionScope.menuAuthentication.helpView || sessionScope.menuAuthentication.qaView}");
    _caucho_expr_61 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${sessionScope.menuAuthentication.helpView}");
    _caucho_expr_62 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${sessionScope.menuAuthentication.qaView}");
    _caucho_expr_63 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${sessionScope.menuAuthentication.qaGroupView}");
    _caucho_expr_64 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${sessionScope.menuAuthentication.submitQaView}");
    _caucho_expr_65 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${sessionScope.menuAuthentication.viewQaView}");
  }

  public void destroy()
  {
      _caucho_isDead = true;
      super.destroy();
  }

  public void init(com.caucho.vfs.Path appDir)
    throws javax.servlet.ServletException
  {
    com.caucho.vfs.Path resinHome = com.caucho.server.util.CauchoSystem.getResinHome();
    com.caucho.vfs.MergePath mergePath = new com.caucho.vfs.MergePath();
    mergePath.addMergePath(appDir);
    mergePath.addMergePath(resinHome);
    com.caucho.loader.DynamicClassLoader loader;
    loader = (com.caucho.loader.DynamicClassLoader) getClass().getClassLoader();
    String resourcePath = loader.getResourcePathSpecificFirst();
    mergePath.addClassPath(resourcePath);
    com.caucho.vfs.Depend depend;
    depend = new com.caucho.vfs.Depend(appDir.lookup("pages/menu.jsp"), -6790926602559257108L, false);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
  }
  private static com.caucho.el.Expr _caucho_expr_0;
  private static com.caucho.el.Expr _caucho_expr_1;
  private static com.caucho.el.Expr _caucho_expr_2;
  private static com.caucho.el.Expr _caucho_expr_3;
  private static com.caucho.el.Expr _caucho_expr_4;
  private static com.caucho.el.Expr _caucho_expr_5;
  private static com.caucho.el.Expr _caucho_expr_6;
  private static com.caucho.el.Expr _caucho_expr_7;
  private static com.caucho.el.Expr _caucho_expr_8;
  private static com.caucho.el.Expr _caucho_expr_9;
  private static com.caucho.el.Expr _caucho_expr_10;
  private static com.caucho.el.Expr _caucho_expr_11;
  private static com.caucho.el.Expr _caucho_expr_12;
  private static com.caucho.el.Expr _caucho_expr_13;
  private static com.caucho.el.Expr _caucho_expr_14;
  private static com.caucho.el.Expr _caucho_expr_15;
  private static com.caucho.el.Expr _caucho_expr_16;
  private static com.caucho.el.Expr _caucho_expr_17;
  private static com.caucho.el.Expr _caucho_expr_18;
  private static com.caucho.el.Expr _caucho_expr_19;
  private static com.caucho.el.Expr _caucho_expr_20;
  private static com.caucho.el.Expr _caucho_expr_21;
  private static com.caucho.el.Expr _caucho_expr_22;
  private static com.caucho.el.Expr _caucho_expr_23;
  private static com.caucho.el.Expr _caucho_expr_24;
  private static com.caucho.el.Expr _caucho_expr_25;
  private static com.caucho.el.Expr _caucho_expr_26;
  private static com.caucho.el.Expr _caucho_expr_27;
  private static com.caucho.el.Expr _caucho_expr_28;
  private static com.caucho.el.Expr _caucho_expr_29;
  private static com.caucho.el.Expr _caucho_expr_30;
  private static com.caucho.el.Expr _caucho_expr_31;
  private static com.caucho.el.Expr _caucho_expr_32;
  private static com.caucho.el.Expr _caucho_expr_33;
  private static com.caucho.el.Expr _caucho_expr_34;
  private static com.caucho.el.Expr _caucho_expr_35;
  private static com.caucho.el.Expr _caucho_expr_36;
  private static com.caucho.el.Expr _caucho_expr_37;
  private static com.caucho.el.Expr _caucho_expr_38;
  private static com.caucho.el.Expr _caucho_expr_39;
  private static com.caucho.el.Expr _caucho_expr_40;
  private static com.caucho.el.Expr _caucho_expr_41;
  private static com.caucho.el.Expr _caucho_expr_42;
  private static com.caucho.el.Expr _caucho_expr_43;
  private static com.caucho.el.Expr _caucho_expr_44;
  private static com.caucho.el.Expr _caucho_expr_45;
  private static com.caucho.el.Expr _caucho_expr_46;
  private static com.caucho.el.Expr _caucho_expr_47;
  private static com.caucho.el.Expr _caucho_expr_48;
  private static com.caucho.el.Expr _caucho_expr_49;
  private static com.caucho.el.Expr _caucho_expr_50;
  private static com.caucho.el.Expr _caucho_expr_51;
  private static com.caucho.el.Expr _caucho_expr_52;
  private static com.caucho.el.Expr _caucho_expr_53;
  private static com.caucho.el.Expr _caucho_expr_54;
  private static com.caucho.el.Expr _caucho_expr_55;
  private static com.caucho.el.Expr _caucho_expr_56;
  private static com.caucho.el.Expr _caucho_expr_57;
  private static com.caucho.el.Expr _caucho_expr_58;
  private static com.caucho.el.Expr _caucho_expr_59;
  private static com.caucho.el.Expr _caucho_expr_60;
  private static com.caucho.el.Expr _caucho_expr_61;
  private static com.caucho.el.Expr _caucho_expr_62;
  private static com.caucho.el.Expr _caucho_expr_63;
  private static com.caucho.el.Expr _caucho_expr_64;
  private static com.caucho.el.Expr _caucho_expr_65;

  private final static char []_jsp_string48;
  private final static char []_jsp_string32;
  private final static char []_jsp_string68;
  private final static char []_jsp_string37;
  private final static char []_jsp_string2;
  private final static char []_jsp_string27;
  private final static char []_jsp_string75;
  private final static char []_jsp_string82;
  private final static char []_jsp_string30;
  private final static char []_jsp_string4;
  private final static char []_jsp_string85;
  private final static char []_jsp_string55;
  private final static char []_jsp_string91;
  private final static char []_jsp_string54;
  private final static char []_jsp_string36;
  private final static char []_jsp_string18;
  private final static char []_jsp_string94;
  private final static char []_jsp_string45;
  private final static char []_jsp_string44;
  private final static char []_jsp_string50;
  private final static char []_jsp_string49;
  private final static char []_jsp_string13;
  private final static char []_jsp_string40;
  private final static char []_jsp_string95;
  private final static char []_jsp_string25;
  private final static char []_jsp_string39;
  private final static char []_jsp_string51;
  private final static char []_jsp_string28;
  private final static char []_jsp_string33;
  private final static char []_jsp_string35;
  private final static char []_jsp_string70;
  private final static char []_jsp_string3;
  private final static char []_jsp_string1;
  private final static char []_jsp_string89;
  private final static char []_jsp_string58;
  private final static char []_jsp_string62;
  private final static char []_jsp_string5;
  private final static char []_jsp_string23;
  private final static char []_jsp_string43;
  private final static char []_jsp_string26;
  private final static char []_jsp_string41;
  private final static char []_jsp_string56;
  private final static char []_jsp_string52;
  private final static char []_jsp_string93;
  private final static char []_jsp_string17;
  private final static char []_jsp_string11;
  private final static char []_jsp_string6;
  private final static char []_jsp_string12;
  private final static char []_jsp_string38;
  private final static char []_jsp_string73;
  private final static char []_jsp_string81;
  private final static char []_jsp_string69;
  private final static char []_jsp_string79;
  private final static char []_jsp_string61;
  private final static char []_jsp_string46;
  private final static char []_jsp_string24;
  private final static char []_jsp_string8;
  private final static char []_jsp_string84;
  private final static char []_jsp_string9;
  private final static char []_jsp_string60;
  private final static char []_jsp_string16;
  private final static char []_jsp_string66;
  private final static char []_jsp_string10;
  private final static char []_jsp_string86;
  private final static char []_jsp_string78;
  private final static char []_jsp_string42;
  private final static char []_jsp_string72;
  private final static char []_jsp_string76;
  private final static char []_jsp_string59;
  private final static char []_jsp_string29;
  private final static char []_jsp_string90;
  private final static char []_jsp_string87;
  private final static char []_jsp_string21;
  private final static char []_jsp_string65;
  private final static char []_jsp_string53;
  private final static char []_jsp_string77;
  private final static char []_jsp_string88;
  private final static char []_jsp_string80;
  private final static char []_jsp_string71;
  private final static char []_jsp_string20;
  private final static char []_jsp_string0;
  private final static char []_jsp_string34;
  private final static char []_jsp_string47;
  private final static char []_jsp_string15;
  private final static char []_jsp_string22;
  private final static char []_jsp_string19;
  private final static char []_jsp_string92;
  private final static char []_jsp_string14;
  private final static char []_jsp_string74;
  private final static char []_jsp_string57;
  private final static char []_jsp_string7;
  private final static char []_jsp_string31;
  private final static char []_jsp_string64;
  private final static char []_jsp_string63;
  private final static char []_jsp_string83;
  private final static char []_jsp_string67;
  static {
    _jsp_string48 = "\n                                { \"data\" : \"Structured Transfer\", \"metadata\" :{id:\"../logs/structured_transfer.action\"} }\n                             ".toCharArray();
    _jsp_string32 = "\n                            { \"data\" : \"Submit Unstructured\", \"metadata\" :{id:\"../dataset/submit_unstructured.action\"} }\n                            ".toCharArray();
    _jsp_string68 = "\n                        ".toCharArray();
    _jsp_string37 = "\n                                ".toCharArray();
    _jsp_string2 = "\n                ".toCharArray();
    _jsp_string27 = "\n                            ,{ \"data\" : \"View Submitted Structured\", \"metadata\" :{id:\"../dataset/view_submitted_structured.action\"} }\n                            ".toCharArray();
    _jsp_string75 = "\n                        { \"data\" : \"System\", \"metadata\" :{id:\"../configuration/system.action\"} },\n                        ".toCharArray();
    _jsp_string82 = "\n                    ]\n                 }\n                ".toCharArray();
    _jsp_string30 = "\n                            ]\n                 }\n                ".toCharArray();
    _jsp_string4 = "\n                , { \"data\" : \"SFIs Management\", \"metadata\" : { id : \"#\" },\n                  \"children\" : [\n                    ".toCharArray();
    _jsp_string85 = "\n                ,{ \"data\" : \"Help\", \"metadata\" :{id:\"#\"},\n                      \"children\" : [\n                          ".toCharArray();
    _jsp_string55 = "\n                                { \"data\" : \"Executive Report\", \"metadata\" :{id:\"../report/executive_report.action\"} }\n                            ".toCharArray();
    _jsp_string91 = ",{ \"data\" : \"Submit Question & Answer\", \"metadata\" :{id:\"../system/submit_question_answer.action\"} }".toCharArray();
    _jsp_string54 = "\n                ,{ \"data\" : \"Report\", \"metadata\" : { id : \"#\" },\n                  \"children\" : [\n                            ".toCharArray();
    _jsp_string36 = "\n                                   { \"data\" : \"Publish Document Group\", \"metadata\" : {id:\"../category/publish_document.action\"} }\n                                ".toCharArray();
    _jsp_string18 = "\n                            ]\n                        }\n                    ".toCharArray();
    _jsp_string94 = "\n                      ]\n                 }\n                 ".toCharArray();
    _jsp_string45 = "\n                          ]\n                     }\n               ".toCharArray();
    _jsp_string44 = "\n                            ,{ \"data\" : \"Composite Rating and Input\", \"metadata\" : {id:\"../composite/composite_rating.action\"} }\n                            ".toCharArray();
    _jsp_string50 = "\n                             ".toCharArray();
    _jsp_string49 = "\n                                ,{ \"data\" : \"Adjust Structured Transfer\", \"metadata\" :{id:\"../logs/adjust_structured_transfer.action\"} }\n                             ".toCharArray();
    _jsp_string13 = "\n                                      ,{ \"data\" : \"ISIC Code\", \"metadata\" :{id:\"../category/isic_version.action\"} }\n                                    ".toCharArray();
    _jsp_string40 = "\n                              ]\n                    }\n               ".toCharArray();
    _jsp_string95 = "\n\n                    ]\n                }\n            ]\n        },\n            \"plugins\" : [ \"themes\", \"json_data\", \"ui\" ] })\n                .bind(\"select_node.jstree\", function (e, data) {\n                    var state = data.inst.is_open(data.rslt.obj);\n                    var webPaths = data.rslt.obj.data(\"id\");\n                    if (state) { data.inst.close_node(data.rslt.obj); }\n                    else { data.inst.open_node(data.rslt.obj); }\n                    if (webPaths != '#' && webPaths!= 'logout') { parent.bodyFrame.location = webPaths; }\n                    else if(webPaths == 'logout'){logout();}\n                });\n            });\n      function logout() {\n        if (confirm(\"Are you sure you want to log out?\")) {\n           parent.bodyFrame.location = '../account/logout.action';\n        }\n    }\n       \n    </script>\n      <style type=\"text/css\">\n        html, body {\n            font-family:		tahoma, helv, arial, verdana, sans-serif;\n            font-size:			11px;\n\n            /*font-size: 11px;*/\n            /*font-family: \"Ms Sans Serif\";*/\n            overflow-x: hidden;\n            overflow-y: hidden;\n            margin:0px;\n            padding:0px;\n            height: 100%;\n            border: none;\n        }\n        table {\n            margin:0px;\n            padding:0px;\n         }\n    </style>\n   <script type=\"text/javascript\" language=\"javascript\">\n       $(function() {\n           $(this).bind(\"contextmenu\", function(e) {\n               e.preventDefault();\n           });\n       });\n   </script>\n  </head>\n  <body>\n   <div id=\"menuTree\" style=\"padding-top:0px;scrolling:auto;overflow-y:auto;background-color:lightblue;width:250px;height:100%\"></div>\n  </body>\n</html>".toCharArray();
    _jsp_string25 = "\n                ,{ \"data\" : \"Structured Dataset Submission\", \"metadata\" : { id : \"#\" },\n                 \"children\" : [\n                            ".toCharArray();
    _jsp_string39 = "\n                                    ,{ \"data\" : \"View Publish Document\", \"metadata\" : {id:\"../publish/view_publish_document.action\"} }\n                                ".toCharArray();
    _jsp_string51 = "\n                               ,{ \"data\" : \"Activity\", \"metadata\" :{id:\"../logs/activity.action\"} }\n                             ".toCharArray();
    _jsp_string28 = "\n                            ,{ \"data\" : \"Submit Adjust\", \"metadata\" :{id:\"../dataset/submit_adjust.action\"} }\n                            ".toCharArray();
    _jsp_string33 = "\n                            ,{ \"data\" : \"View Submitted Unstructured\", \"metadata\" :{id:\"../dataset/view_submitted_unstructured.action\"} }\n                            ".toCharArray();
    _jsp_string35 = "\n                 , { \"data\" : \"Publish Document Submission\", \"metadata\" : { id : \"#\" },\n                  \"children\" : [\n                                ".toCharArray();
    _jsp_string70 = "\n                      ".toCharArray();
    _jsp_string3 = "\n                   , { \"data\" : \"User Management\", \"metadata\" : { id : \"../user/user_management.action\" } }\n                ".toCharArray();
    _jsp_string1 = "\n                    { \"data\" : \"News & Information\", \"metadata\" : { id : \"../news/news_information.action\" } }\n                ".toCharArray();
    _jsp_string89 = " { \"data\" : \"Question Group\", \"metadata\" :{id:\"../system/question_answer_group.action\"} }".toCharArray();
    _jsp_string58 = "\n\n                            //TODO: add menu kpi\n                            ".toCharArray();
    _jsp_string62 = "\n                               ,{ \"data\" : \"KPI UnStructured Report\", \"metadata\" :{id:\"../report/kpi_report_unstructured.action\"} }\n                            ".toCharArray();
    _jsp_string5 = "\n                        { \"data\" : \"SFIs Management\", \"metadata\" :{id:\"../sfis/sfi_management.action\"} },\n                    ".toCharArray();
    _jsp_string23 = "\n                   ]\n                 }\n                ".toCharArray();
    _jsp_string43 = "\n                             { \"data\" : \"Upload CSV File for BI\", \"metadata\" : { id : \"../csv/csv_upload_view.action\" }  }\n                            ".toCharArray();
    _jsp_string26 = "\n                            { \"data\" : \"Submit Structured\", \"metadata\" :{id:\"../dataset/submit_structured.action\"} }\n                            ".toCharArray();
    _jsp_string41 = "\n               ".toCharArray();
    _jsp_string56 = "\n                               ,{ \"data\" : \"KPI Structured Report\", \"metadata\" :{id:\"../report/kpi_report_structured.action\"} }\n                            ".toCharArray();
    _jsp_string52 = "\n                               ,{ \"data\" : \"Document Status Structured\", \"metadata\" :{id:\"../logs/document_status_log.action\"} }\n                             ".toCharArray();
    _jsp_string93 = "\n                              ]\n                          }\n                          ".toCharArray();
    _jsp_string17 = "\n                            ".toCharArray();
    _jsp_string11 = "\n                                    ".toCharArray();
    _jsp_string6 = "\n                    ".toCharArray();
    _jsp_string12 = "\n                                        { \"data\" : \"Classification\", \"metadata\" :{id:\"../category/classification_version.action\"} }\n                                    ".toCharArray();
    _jsp_string38 = "\n                                    ,{ \"data\" : \"Submit Publish Document\", \"metadata\" : {id:\"../publish/submit_publish_document.action\"} }\n                                ".toCharArray();
    _jsp_string73 = "\n                                ]\n                 }\n                ".toCharArray();
    _jsp_string81 = "\n                        { \"data\" : \"No Transaction\", \"metadata\" :{id:\"../configuration/no_transaction.action\"} }\n                        ".toCharArray();
    _jsp_string69 = "\n                            ,{ \"data\" : \"Export Data\", \"metadata\" :{id:\"../export/export_data.action\"} }\n                        ".toCharArray();
    _jsp_string79 = "\n                        { \"data\" : \"Sending Waive UnStructured\", \"metadata\" :{id:\"../configuration/sending_waive_unstructure.action\"} },\n                        ".toCharArray();
    _jsp_string61 = "\n\n                            ".toCharArray();
    _jsp_string46 = "\n\n              ".toCharArray();
    _jsp_string24 = "\n\n                ".toCharArray();
    _jsp_string8 = "\n                    ]\n                }\n                ".toCharArray();
    _jsp_string84 = "\n                ,{ \"data\" : \"System\", \"metadata\" : { id : \"#\" },\n                  \"children\" : [\n                    { \"data\" : \"Change Password\", \"metadata\" :{id:\"../system/change_password.action\"} },\n                    { \"data\" : \"Log out\", \"metadata\" :{id:\"logout\"} }\n                ".toCharArray();
    _jsp_string9 = "\n                ,{ \"data\" : \"Document Category\", \"metadata\" : { id : \"#\" },\n                  \"children\" : [\n                    ".toCharArray();
    _jsp_string60 = "\n                              ,{ \"data\" : \"KPI Structured By Search (BOT Status)\", \"metadata\" :{id:\"../report/kpi_report_structured_by_search_bot.action\"} }\n                            ".toCharArray();
    _jsp_string16 = "\n                                        ,{ \"data\" : \"Rules Validation\", \"metadata\" :{id:\"../category/rules_validation.action\"} }\n                                    ".toCharArray();
    _jsp_string66 = "\n               , { \"data\" : \"Export Data\", \"metadata\" : { id : \"#\" },\n                  \"children\" : [\n                        ".toCharArray();
    _jsp_string10 = "\n                        { \"data\" : \"Structured Dataset\", \"metadata\" :{id:\"../category/structured_dataset.action\"},\n                          \"children\" : [\n                            ".toCharArray();
    _jsp_string86 = "\n                           { \"data\" : \"Help\", \"metadata\" :{id:\"../system/help.action\"} }\n                          ".toCharArray();
    _jsp_string78 = "\n                        { \"data\" : \"Sending Waive Structured\", \"metadata\" :{id:\"../configuration/sending_waive.action\"} },\n                        ".toCharArray();
    _jsp_string42 = "\n                    , { \"data\" : \"Data for BI\", \"metadata\" : { id : \"#\" } ,\n                    \"children\" :[\n                            ".toCharArray();
    _jsp_string72 = "\n                        ,{ \"data\" : \"Export Unstructured\", \"metadata\" :{id:\"../export/export_unstructured.action\"} }\n                      ".toCharArray();
    _jsp_string76 = "\n                        { \"data\" : \"Frequency Structured\", \"metadata\" :{id:\"../configuration/frequency_config.action\"} },\n                        ".toCharArray();
    _jsp_string59 = "\n                              ,{ \"data\" : \"KPI Structured Report (BOT Status)\", \"metadata\" :{id:\"../report/kpi_report_structured_bot.action\"} }\n                            ".toCharArray();
    _jsp_string29 = "\n                            ,{ \"data\" : \"View Submitted Adjust\", \"metadata\" :{id:\"../dataset/view_submitted_adjust.action\"} }\n                            ".toCharArray();
    _jsp_string90 = "\n                                  ".toCharArray();
    _jsp_string87 = "\n                          ".toCharArray();
    _jsp_string21 = "\n                  ".toCharArray();
    _jsp_string65 = "\n                               ,{ \"data\" : \"Export Log Report\", \"metadata\" :{id:\"../report/export_log_report.action\"} }\n                            ".toCharArray();
    _jsp_string53 = "\n                               ,{ \"data\" : \"Document Status Unstructured\", \"metadata\" :{id:\"../logs/document_status_log_unstructured.action\"} }\n                             ".toCharArray();
    _jsp_string77 = "\n                         { \"data\" : \"Frequency UnStructured\", \"metadata\" :{id:\"../configuration/frequency_unstructured.action\"} },\n                        ".toCharArray();
    _jsp_string88 = "\n                          ,{ \"data\" : \"Question & Answer\", \"metadata\" :{id:\"#\"},\n                              \"children\" : [\n                                  ".toCharArray();
    _jsp_string80 = "\n                        { \"data\" : \"Official Holiday\", \"metadata\" :{id:\"../configuration/official_holiday.action\"} },\n                        ".toCharArray();
    _jsp_string71 = "\n                        ,{ \"data\" : \"Defined Unstructured\", \"metadata\" :{id:\"../export/defined_unstructured.action\"} }\n                      ".toCharArray();
    _jsp_string20 = "\n                        ,{ \"data\" : \"Unstructured Dataset\", \"metadata\" :{id:\"../category/unstructure_version.action\"} }\n                   ".toCharArray();
    _jsp_string0 = "\n\n\n\n\n<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Strict//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd\">\n<html xmlns=\"http://www.w3.org/1999/xhtml\">\n  <head>\n   <title>Specialized Financial Institutions Information System</title>\n\n   <script type=\"text/javascript\" src=\"../includes/js/tp/utils.js\"></script>\n    <script type=\"text/javascript\" src=\"../includes/jsTree/_lib/jquery.js\"></script>\n    <script type=\"text/javascript\" src=\"../includes/jsTree/jquery.jstree.js\"></script>\n   <script type=\"text/javascript\" class=\"source below\">\n    $(function () {\n        $(\"#menuTree\").jstree({ \"json_data\" : {\n            \"data\" : [\n                { \"data\" : \"Home\", \"metadata\" : { id : \"../home/home.action\" }},\n                ".toCharArray();
    _jsp_string34 = "\n                  ]\n                }\n                ".toCharArray();
    _jsp_string47 = "\n                , { \"data\" : \"Logs\", \"metadata\" : { id : \"#\" },\n                    \"children\" : [\n                             ".toCharArray();
    _jsp_string15 = "\n                                        ,{ \"data\" : \"Report Type\", \"metadata\" :{id:\"../category/report_type.action\"} }\n                                    ".toCharArray();
    _jsp_string22 = "\n                        ,{ \"data\" : \"Move File Unstructured Dataset\", \"metadata\" :{id:\"../category/move_file_unstructured_dataset.action\"} }\n                  ".toCharArray();
    _jsp_string19 = "\n                   ".toCharArray();
    _jsp_string92 = ",{ \"data\" : \"View Question & Answer\", \"metadata\" :{id:\"../system/view_question_answer.action\"} }".toCharArray();
    _jsp_string14 = "\n                                        ,{ \"data\" : \"Government Agency Code\", \"metadata\" :{id:\"../category/government_agency_code.action\"} }\n                                    ".toCharArray();
    _jsp_string74 = "\n                ,{ \"data\" : \"Configuration\", \"metadata\" : { id : \"#\" },\n                  \"children\" : [\n                     ".toCharArray();
    _jsp_string57 = "\n                              ,{ \"data\" : \"KPI Structured By Search\", \"metadata\" :{id:\"../report/kpi_report_structured_by_search.action\"} }\n                            ".toCharArray();
    _jsp_string7 = "\n                        ,{ \"data\" : \"Branch Code\", \"metadata\" :{id:\"../sfis/branch_code.action\"} }\n                    ".toCharArray();
    _jsp_string31 = "\n                , { \"data\" : \"Unstructured Dataset Submission\", \"metadata\" : { id : \"#\" },\n                  \"children\" : [\n                            ".toCharArray();
    _jsp_string64 = "\n                               ,{ \"data\" : \"Monitoring Unstructured\", \"metadata\" :{id:\"../report/monitoring_unstructured.action\"} }\n                            ".toCharArray();
    _jsp_string63 = "\n                               ,{ \"data\" : \"Monitoring Structured\", \"metadata\" :{id:\"../report/monitoring_report.action\"} }\n                            ".toCharArray();
    _jsp_string83 = "\n                , { \"data\" : \"Defect Log\", \"metadata\" : { id : \"../defectLog/defect_log.action\" } }\n                ".toCharArray();
    _jsp_string67 = "\n                            {  \"data\" : \"Defined Data\", \"metadata\" :{id:\"../export/defined_data.action\"} }\n                        ".toCharArray();
  }
}
