/*
 * JSP generated by Resin-3.1.9 (built Mon, 13 Apr 2009 11:09:12 PDT)
 */

package _jsp._system;
import javax.servlet.*;
import javax.servlet.jsp.*;
import javax.servlet.http.*;

public class _change_0password__jsp extends com.caucho.jsp.JavaPage
{
  private static final java.util.HashMap<String,java.lang.reflect.Method> _jsp_functionMap = new java.util.HashMap<String,java.lang.reflect.Method>();
  private boolean _caucho_isDead;
  
  public void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response)
    throws java.io.IOException, javax.servlet.ServletException
  {
    javax.servlet.http.HttpSession session = request.getSession(true);
    com.caucho.server.webapp.WebApp _jsp_application = _caucho_getApplication();
    javax.servlet.ServletContext application = _jsp_application;
    com.caucho.jsp.PageContextImpl pageContext = _jsp_application.getJspApplicationContext().allocatePageContext(this, _jsp_application, request, response, null, session, 8192, true, false);
    javax.servlet.jsp.PageContext _jsp_parentContext = pageContext;
    javax.servlet.jsp.JspWriter out = pageContext.getOut();
    final javax.el.ELContext _jsp_env = pageContext.getELContext();
    javax.servlet.ServletConfig config = getServletConfig();
    javax.servlet.Servlet page = this;
    response.setContentType("text/html;charset=UTF-8");
    request.setCharacterEncoding("UTF-8");
    org.apache.struts2.views.jsp.ui.FormTag _jsp_FormTag_0 = null;
    org.apache.struts2.views.jsp.PropertyTag _jsp_PropertyTag_1 = null;
    org.apache.struts2.views.jsp.ui.PasswordTag _jsp_PasswordTag_2 = null;
    org.apache.struts2.views.jsp.ui.SubmitTag _jsp_SubmitTag_3 = null;
    try {
      out.write(_jsp_string0, 0, _jsp_string0.length);
      com.caucho.jsp.BodyContentImpl _jsp_endTagHack0 = null;
      if (_jsp_FormTag_0 == null) {
        _jsp_FormTag_0 = new org.apache.struts2.views.jsp.ui.FormTag();
        _jsp_FormTag_0.setPageContext(pageContext);
        _jsp_FormTag_0.setParent((javax.servlet.jsp.tagext.Tag) null);
        _jsp_FormTag_0.setAction("change_password");
      }

      int _jspEval2 = _jsp_FormTag_0.doStartTag();
      if (_jspEval2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        if (_jspEval2 == javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_BUFFERED) {
          out = pageContext.pushBody();
          _jsp_endTagHack0 = (com.caucho.jsp.BodyContentImpl) out;
          _jsp_FormTag_0.setBodyContent(_jsp_endTagHack0);
        }
        out.write(_jsp_string1, 0, _jsp_string1.length);
        if (_jsp_PropertyTag_1 == null) {
          _jsp_PropertyTag_1 = new org.apache.struts2.views.jsp.PropertyTag();
          _jsp_PropertyTag_1.setPageContext(pageContext);
          _jsp_PropertyTag_1.setParent((javax.servlet.jsp.tagext.Tag) _jsp_FormTag_0);
          _jsp_PropertyTag_1.setValue("errorMassage");
        }

        int _jspEval5 = _jsp_PropertyTag_1.doStartTag();
        _jsp_PropertyTag_1.doEndTag();
        out.write(_jsp_string2, 0, _jsp_string2.length);
        if (_jsp_PasswordTag_2 == null) {
          _jsp_PasswordTag_2 = new org.apache.struts2.views.jsp.ui.PasswordTag();
          _jsp_PasswordTag_2.setPageContext(pageContext);
          _jsp_PasswordTag_2.setParent((javax.servlet.jsp.tagext.Tag) _jsp_FormTag_0);
        }

        _jsp_PasswordTag_2.setName("oldPassword");
        _jsp_PasswordTag_2.setId("oldPassword");
        int _jspEval9 = _jsp_PasswordTag_2.doStartTag();
        _jsp_PasswordTag_2.doEndTag();
        out.write(_jsp_string3, 0, _jsp_string3.length);
        _jsp_PasswordTag_2.setName("newPassword");
        _jsp_PasswordTag_2.setId("newPassword");
        int _jspEval13 = _jsp_PasswordTag_2.doStartTag();
        _jsp_PasswordTag_2.doEndTag();
        out.write(_jsp_string4, 0, _jsp_string4.length);
        _jsp_PasswordTag_2.setName("reTypeNewPassword");
        _jsp_PasswordTag_2.setId("reTypeNewPassword");
        int _jspEval17 = _jsp_PasswordTag_2.doStartTag();
        _jsp_PasswordTag_2.doEndTag();
        out.write(_jsp_string5, 0, _jsp_string5.length);
        if (_jsp_SubmitTag_3 == null) {
          _jsp_SubmitTag_3 = new org.apache.struts2.views.jsp.ui.SubmitTag();
          _jsp_SubmitTag_3.setPageContext(pageContext);
          _jsp_SubmitTag_3.setParent((javax.servlet.jsp.tagext.Tag) _jsp_FormTag_0);
          _jsp_SubmitTag_3.setMethod("save");
          _jsp_SubmitTag_3.setValue("OK");
          _jsp_SubmitTag_3.setCssClass("button");
          _jsp_SubmitTag_3.setOnclick("return validateForm();");
        }

        int _jspEval21 = _jsp_SubmitTag_3.doStartTag();
        _jsp_SubmitTag_3.doEndTag();
        out.write(_jsp_string6, 0, _jsp_string6.length);
        if (_jspEval2 == javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_BUFFERED)
          out = pageContext.popBody();
      }
      _jsp_FormTag_0.doEndTag();
      if (_jsp_endTagHack0 != null) {
        pageContext.releaseBody(_jsp_endTagHack0);
        _jsp_endTagHack0 = null;
      }
      out.write(_jsp_string7, 0, _jsp_string7.length);
    } catch (java.lang.Throwable _jsp_e) {
      pageContext.handlePageException(_jsp_e);
    } finally {
      if (_jsp_FormTag_0 != null)
        _jsp_FormTag_0.release();
      if (_jsp_PropertyTag_1 != null)
        _jsp_PropertyTag_1.release();
      if (_jsp_PasswordTag_2 != null)
        _jsp_PasswordTag_2.release();
      if (_jsp_SubmitTag_3 != null)
        _jsp_SubmitTag_3.release();
      _jsp_application.getJspApplicationContext().freePageContext(pageContext);
    }
  }

  private java.util.ArrayList _caucho_depends = new java.util.ArrayList();

  public java.util.ArrayList _caucho_getDependList()
  {
    return _caucho_depends;
  }

  public void _caucho_addDepend(com.caucho.vfs.PersistentDependency depend)
  {
    super._caucho_addDepend(depend);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
  }

  public boolean _caucho_isModified()
  {
    if (_caucho_isDead)
      return true;
    if (com.caucho.server.util.CauchoSystem.getVersionId() != 5783496155892875126L)
      return true;
    for (int i = _caucho_depends.size() - 1; i >= 0; i--) {
      com.caucho.vfs.Dependency depend;
      depend = (com.caucho.vfs.Dependency) _caucho_depends.get(i);
      if (depend.isModified())
        return true;
    }
    return false;
  }

  public long _caucho_lastModified()
  {
    return 0;
  }

  public java.util.HashMap<String,java.lang.reflect.Method> _caucho_getFunctionMap()
  {
    return _jsp_functionMap;
  }

  public void init(ServletConfig config)
    throws ServletException
  {
    com.caucho.server.webapp.WebApp webApp
      = (com.caucho.server.webapp.WebApp) config.getServletContext();
    super.init(config);
    com.caucho.jsp.TaglibManager manager = webApp.getJspApplicationContext().getTaglibManager();
    manager.addTaglibFunctions(_jsp_functionMap, "s", "/struts-tags");
    com.caucho.jsp.PageContextImpl pageContext = new com.caucho.jsp.PageContextImpl(webApp, this);
  }

  public void destroy()
  {
      _caucho_isDead = true;
      super.destroy();
  }

  public void init(com.caucho.vfs.Path appDir)
    throws javax.servlet.ServletException
  {
    com.caucho.vfs.Path resinHome = com.caucho.server.util.CauchoSystem.getResinHome();
    com.caucho.vfs.MergePath mergePath = new com.caucho.vfs.MergePath();
    mergePath.addMergePath(appDir);
    mergePath.addMergePath(resinHome);
    com.caucho.loader.DynamicClassLoader loader;
    loader = (com.caucho.loader.DynamicClassLoader) getClass().getClassLoader();
    String resourcePath = loader.getResourcePathSpecificFirst();
    mergePath.addClassPath(resourcePath);
    com.caucho.vfs.Depend depend;
    depend = new com.caucho.vfs.Depend(appDir.lookup("system/change_password.jsp"), -1858512223342096175L, false);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
    depend = new com.caucho.vfs.Depend(mergePath.lookup("jar:file:/J:/sfi-web-resin2/webapps/fsis2015/WEB-INF/lib/struts2-core-2.1.6.jar!/META-INF/struts-tags.tld"), 4562940134640561417L, false);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, new com.caucho.make.ClassDependency(org.apache.struts2.views.jsp.PropertyTag.class, 3385148796796543420L));
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, new com.caucho.make.ClassDependency(org.apache.struts2.views.jsp.ui.PasswordTag.class, -8235161264495238788L));
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, new com.caucho.make.ClassDependency(org.apache.struts2.views.jsp.ui.SubmitTag.class, 2704927420214496830L));
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, new com.caucho.make.ClassDependency(org.apache.struts2.views.jsp.ui.FormTag.class, -3000898630992437772L));
  }

  static {
    try {
    } catch (Exception e) {
      e.printStackTrace();
      throw new RuntimeException(e);
    }
  }

  private final static char []_jsp_string4;
  private final static char []_jsp_string2;
  private final static char []_jsp_string7;
  private final static char []_jsp_string1;
  private final static char []_jsp_string0;
  private final static char []_jsp_string6;
  private final static char []_jsp_string3;
  private final static char []_jsp_string5;
  static {
    _jsp_string4 = "\n                                                </td>\n                                            </tr>\n                                            <tr class=\"bgGreen2\">\n                                                <td align=\"right\">\n                                                    Re-type new password<span class=\"require_field\">*</span> :\n                                                </td>\n                                                <td>\n                                                    ".toCharArray();
    _jsp_string2 = "</b>\n                                                    </font>\n                                                </td>\n                                            </tr>\n                                            <tr>\n                                                <td><b>Change Password</b></td>\n                                            </tr>\n                                        </table>\n                                        <table width=\"100%\" class=\"displayTable\">\n                                            <tr class=\"bgGreen2\">\n                                                <td width=\"25%\" align=\"right\">\n                                                    Old Password<span class=\"require_field\">*</span> :\n                                                </td>\n                                                <td width=\"75%\">\n                                                    ".toCharArray();
    _jsp_string7 = "\n<script type=\"text/javascript\">\n    var thisForm = document.getElementsByTagName('form')[0];\n</script>\n</body>\n</html>\n</body>\n</html>".toCharArray();
    _jsp_string1 = "\n    <table width=\"98%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" align=\"center\">\n        <tr>\n            <td>\n                <table width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\n                    <tr>\n                        <td width=\"43\"><img src=\"../images/table001.gif\" width=\"43\" height=\"43\" alt=\"\"></td>\n                        <td background=\"../images/table002.gif\">&nbsp;</td>\n                        <td width=\"173\"><img src=\"../images/table003.gif\" width=\"173\" height=\"43\" alt=\"\"></td>\n                    </tr>\n                </table>\n            </td>\n        </tr>\n        <tr>\n            <td>\n                <table width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\n                    <tr>\n                        <td width=\"43\" background=\"../images/table004.gif\">\n                            <img src=\"../images/table004.gif\" width=\"43\" height=\"37\" alt=\"\">\n                        </td>\n                        <td>\n                            <table width=\"100%\" border=\"0\" align=\"center\" style=\"height:100%\">\n                                <tr>\n                                    <td>\n                                        \n                                        <table width=\"100%\">\n                                            <tr>\n                                                <td>\n                                                    <font color=\"red\">\n                                                        <b>".toCharArray();
    _jsp_string0 = "\n\n\n<html>\n<head>\n    <title>Simple jsp page</title>\n    <link rel=\"stylesheet\" type=\"text/css\" href=\"../includes/css/style.css\">\n\n    <script language=\"javascript\" src=\"../includes/js/tp/utils.js\"></script>\n    <script language=\"javascript\" src=\"../includes/js/tp/validate.js\"></script>\n    <script type=\"text/javascript\">\n        function checkPassword() {\n            var password1 = document.getElementById('newPassword').value;\n            var password2 = document.getElementById('reTypeNewPassword').value;\n            if (password1 != password2) {\n                return false;\n            }\n            else {\n                return true;\n            }\n        }\n\n        function validateForm() {\n            if (isEmptyById('oldPassword')) {\n                alert('Please Input Old Password !!');\n                thisForm.oldPassword.focus();\n                return false;\n            }\n\n            if (isEmptyById('newPassword')) {\n                alert('Please Input New Password !!');\n                thisForm.newPassword.focus();\n                return false;\n            }\n\n            if (isEmptyById('reTypeNewPassword')) {\n                alert('Please Input New Password Again !!');\n                thisForm.reTypeNewPassword.focus();\n                return false;\n            }\n            if (!checkPassword()) {\n                alert(\"Password Mismatch\");\n                return false;\n            }\n            return true;\n        }\n    </script>\n</head>\n<body>\n".toCharArray();
    _jsp_string6 = "\n                                                </td>\n                                            </tr>\n                                        </table>\n                                        \n                                    </td>\n                                    <td width=\"20px\">&nbsp;</td>\n                                </tr>\n                            </table>\n                        </td>\n                        <td width=\"28\" background=\"../images/table005.gif\"><img src=\"../images/table005.gif\" width=\"28\"\n                                                                                height=\"37\" alt=\"\"></td>\n                    </tr>\n                    <tr>\n                        <td><img src=\"../images/table006.gif\" width=\"43\" height=\"23\" alt=\"\"></td>\n                        <td background=\"../images/table007.gif\"></TD>\n                        <td><img src=\"../images/table008.gif\" width=\"28\" height=\"23\" alt=\"\"></td>\n                    </tr>\n                </table>\n            </td>\n        </tr>\n    </table>\n".toCharArray();
    _jsp_string3 = "\n                                                </td>\n                                            </tr>\n                                            <tr class=\"bgGreen1\">\n                                                <td align=\"right\">\n                                                    New Password<span class=\"require_field\">*</span> :\n                                                </td>\n                                                <td>\n                                                    ".toCharArray();
    _jsp_string5 = "\n                                                </td>\n                                            </tr>\n                                        </table>\n                                        <table width=\"100%\">\n                                            <tr>\n                                                <td width=\"100%\" align=\"center\">\n                                                    ".toCharArray();
  }
}
