<DS_PVS xmlns:x0="http://www.w3.org/2001/XMLSchema" name="Provision Summary" schemaVersion="SFI 5.0"
        type="Fixed CL with sub-repeating">
    <CommonHeader>
        <OrganizationId>066</OrganizationId>
        <DataSetDate>2011-12-31</DataSetDate>
    </CommonHeader>
    <DS_PVS_Header/>
    <DS_PVS_Content>
        <ContentRecordGroup>
            <FiReportingGroupId>116003</FiReportingGroupId>
            <ProvisionSummaryItem960005 name="">
                <ProvisionSummaryItemInfo>
                    <AssetClassificationType>020001</AssetClassificationType>
                    <Amount>0.00</Amount>
                </ProvisionSummaryItemInfo>
                <ProvisionSummaryItemInfo>
                    <AssetClassificationType>020002</AssetClassificationType>
                    <Amount>0.00</Amount>
                </ProvisionSummaryItemInfo>
                <ProvisionSummaryItemInfo>
                    <AssetClassificationType>020003</AssetClassificationType>
                    <Amount>0.00</Amount>
                </ProvisionSummaryItemInfo>
                <ProvisionSummaryItemInfo>
                    <AssetClassificationType>020004</AssetClassificationType>
                    <Amount>0.00</Amount>
                </ProvisionSummaryItemInfo>
                <ProvisionSummaryItemInfo>
                    <AssetClassificationType>020005</AssetClassificationType>
                    <Amount>0.00</Amount>
                </ProvisionSummaryItemInfo>
                <ProvisionSummaryItemInfo>
                    <AssetClassificationType>020006</AssetClassificationType>
                    <Amount>0.00</Amount>
                </ProvisionSummaryItemInfo>
            </ProvisionSummaryItem960005>
            <ProvisionSummaryItem960019 name="">
                <ProvisionSummaryItemInfo>
                    <AssetClassificationType>020001</AssetClassificationType>
                    <Amount>102713579032.36</Amount>
                </ProvisionSummaryItemInfo>
                <ProvisionSummaryItemInfo>
                    <AssetClassificationType>020002</AssetClassificationType>
                    <Amount>4633450979.06</Amount>
                </ProvisionSummaryItemInfo>
                <ProvisionSummaryItemInfo>
                    <AssetClassificationType>020003</AssetClassificationType>
                    <Amount>2934541995.95</Amount>
                </ProvisionSummaryItemInfo>
                <ProvisionSummaryItemInfo>
                    <AssetClassificationType>020004</AssetClassificationType>
                    <Amount>1235708482.60</Amount>
                </ProvisionSummaryItemInfo>
                <ProvisionSummaryItemInfo>
                    <AssetClassificationType>020005</AssetClassificationType>
                    <Amount>3452860085.23</Amount>
                </ProvisionSummaryItemInfo>
                <ProvisionSummaryItemInfo>
                    <AssetClassificationType>020006</AssetClassificationType>
                    <Amount>0.00</Amount>
                </ProvisionSummaryItemInfo>
            </ProvisionSummaryItem960019>
            <ProvisionSummaryItem960020 name="">
                <ProvisionSummaryItemInfo>
                    <AssetClassificationType>020001</AssetClassificationType>
                    <Amount>0.00</Amount>
                </ProvisionSummaryItemInfo>
                <ProvisionSummaryItemInfo>
                    <AssetClassificationType>020002</AssetClassificationType>
                    <Amount>0.00</Amount>
                </ProvisionSummaryItemInfo>
                <ProvisionSummaryItemInfo>
                    <AssetClassificationType>020003</AssetClassificationType>
                    <Amount>0.00</Amount>
                </ProvisionSummaryItemInfo>
                <ProvisionSummaryItemInfo>
                    <AssetClassificationType>020004</AssetClassificationType>
                    <Amount>0.00</Amount>
                </ProvisionSummaryItemInfo>
                <ProvisionSummaryItemInfo>
                    <AssetClassificationType>020005</AssetClassificationType>
                    <Amount>0.00</Amount>
                </ProvisionSummaryItemInfo>
                <ProvisionSummaryItemInfo>
                    <AssetClassificationType>020006</AssetClassificationType>
                    <Amount>0.00</Amount>
                </ProvisionSummaryItemInfo>
            </ProvisionSummaryItem960020>
            <ProvisionSummaryItem960004 name="">
                <ProvisionSummaryItemInfo>
                    <AssetClassificationType>020001</AssetClassificationType>
                    <Amount>0.00</Amount>
                </ProvisionSummaryItemInfo>
                <ProvisionSummaryItemInfo>
                    <AssetClassificationType>020002</AssetClassificationType>
                    <Amount>0.00</Amount>
                </ProvisionSummaryItemInfo>
                <ProvisionSummaryItemInfo>
                    <AssetClassificationType>020003</AssetClassificationType>
                    <Amount>0.00</Amount>
                </ProvisionSummaryItemInfo>
                <ProvisionSummaryItemInfo>
                    <AssetClassificationType>020004</AssetClassificationType>
                    <Amount>0.00</Amount>
                </ProvisionSummaryItemInfo>
                <ProvisionSummaryItemInfo>
                    <AssetClassificationType>020005</AssetClassificationType>
                    <Amount>0.00</Amount>
                </ProvisionSummaryItemInfo>
                <ProvisionSummaryItemInfo>
                    <AssetClassificationType>020006</AssetClassificationType>
                    <Amount>0.00</Amount>
                </ProvisionSummaryItemInfo>
            </ProvisionSummaryItem960004>
            <ProvisionSummaryItem960006 name="">
                <ProvisionSummaryItemInfo>
                    <AssetClassificationType>020001</AssetClassificationType>
                    <Amount>0.00</Amount>
                </ProvisionSummaryItemInfo>
                <ProvisionSummaryItemInfo>
                    <AssetClassificationType>020002</AssetClassificationType>
                    <Amount>0.00</Amount>
                </ProvisionSummaryItemInfo>
                <ProvisionSummaryItemInfo>
                    <AssetClassificationType>020003</AssetClassificationType>
                    <Amount>0.00</Amount>
                </ProvisionSummaryItemInfo>
                <ProvisionSummaryItemInfo>
                    <AssetClassificationType>020004</AssetClassificationType>
                    <Amount>0.00</Amount>
                </ProvisionSummaryItemInfo>
                <ProvisionSummaryItemInfo>
                    <AssetClassificationType>020005</AssetClassificationType>
                    <Amount>0.00</Amount>
                </ProvisionSummaryItemInfo>
                <ProvisionSummaryItemInfo>
                    <AssetClassificationType>020006</AssetClassificationType>
                    <Amount>0.00</Amount>
                </ProvisionSummaryItemInfo>
            </ProvisionSummaryItem960006>
            <ProvisionSummaryItem960007 name="">
                <ProvisionSummaryItemInfo>
                    <AssetClassificationType>020001</AssetClassificationType>
                    <Amount>0.00</Amount>
                </ProvisionSummaryItemInfo>
                <ProvisionSummaryItemInfo>
                    <AssetClassificationType>020002</AssetClassificationType>
                    <Amount>0.00</Amount>
                </ProvisionSummaryItemInfo>
                <ProvisionSummaryItemInfo>
                    <AssetClassificationType>020003</AssetClassificationType>
                    <Amount>0.00</Amount>
                </ProvisionSummaryItemInfo>
                <ProvisionSummaryItemInfo>
                    <AssetClassificationType>020004</AssetClassificationType>
                    <Amount>0.00</Amount>
                </ProvisionSummaryItemInfo>
                <ProvisionSummaryItemInfo>
                    <AssetClassificationType>020005</AssetClassificationType>
                    <Amount>0.00</Amount>
                </ProvisionSummaryItemInfo>
                <ProvisionSummaryItemInfo>
                    <AssetClassificationType>020006</AssetClassificationType>
                    <Amount>0.00</Amount>
                </ProvisionSummaryItemInfo>
            </ProvisionSummaryItem960007>
            <ProvisionSummaryItem960021 name="">
                <ProvisionSummaryItemInfo>
                    <AssetClassificationType>020001</AssetClassificationType>
                    <Amount>0.00</Amount>
                </ProvisionSummaryItemInfo>
                <ProvisionSummaryItemInfo>
                    <AssetClassificationType>020002</AssetClassificationType>
                    <Amount>0.00</Amount>
                </ProvisionSummaryItemInfo>
                <ProvisionSummaryItemInfo>
                    <AssetClassificationType>020003</AssetClassificationType>
                    <Amount>0.00</Amount>
                </ProvisionSummaryItemInfo>
                <ProvisionSummaryItemInfo>
                    <AssetClassificationType>020004</AssetClassificationType>
                    <Amount>0.00</Amount>
                </ProvisionSummaryItemInfo>
                <ProvisionSummaryItemInfo>
                    <AssetClassificationType>020005</AssetClassificationType>
                    <Amount>0.00</Amount>
                </ProvisionSummaryItemInfo>
                <ProvisionSummaryItemInfo>
                    <AssetClassificationType>020006</AssetClassificationType>
                    <Amount>0.00</Amount>
                </ProvisionSummaryItemInfo>
            </ProvisionSummaryItem960021>
            <ProvisionSummaryItem960022 name="">
                <ProvisionSummaryItemInfo>
                    <AssetClassificationType>020001</AssetClassificationType>
                    <Amount>66827022708.20</Amount>
                </ProvisionSummaryItemInfo>
                <ProvisionSummaryItemInfo>
                    <AssetClassificationType>020002</AssetClassificationType>
                    <Amount>7638977043.78</Amount>
                </ProvisionSummaryItemInfo>
                <ProvisionSummaryItemInfo>
                    <AssetClassificationType>020003</AssetClassificationType>
                    <Amount>1626212935.00</Amount>
                </ProvisionSummaryItemInfo>
                <ProvisionSummaryItemInfo>
                    <AssetClassificationType>020004</AssetClassificationType>
                    <Amount>832698049.35</Amount>
                </ProvisionSummaryItemInfo>
                <ProvisionSummaryItemInfo>
                    <AssetClassificationType>020005</AssetClassificationType>
                    <Amount>2123941161.17</Amount>
                </ProvisionSummaryItemInfo>
                <ProvisionSummaryItemInfo>
                    <AssetClassificationType>020006</AssetClassificationType>
                    <Amount>0.00</Amount>
                </ProvisionSummaryItemInfo>
            </ProvisionSummaryItem960022>
            <ProvisionSummaryItem960023 name="">
                <ProvisionSummaryItemInfo>
                    <AssetClassificationType>020001</AssetClassificationType>
                    <Amount>0.00</Amount>
                </ProvisionSummaryItemInfo>
                <ProvisionSummaryItemInfo>
                    <AssetClassificationType>020002</AssetClassificationType>
                    <Amount>0.00</Amount>
                </ProvisionSummaryItemInfo>
                <ProvisionSummaryItemInfo>
                    <AssetClassificationType>020003</AssetClassificationType>
                    <Amount>0.00</Amount>
                </ProvisionSummaryItemInfo>
                <ProvisionSummaryItemInfo>
                    <AssetClassificationType>020004</AssetClassificationType>
                    <Amount>0.00</Amount>
                </ProvisionSummaryItemInfo>
                <ProvisionSummaryItemInfo>
                    <AssetClassificationType>020005</AssetClassificationType>
                    <Amount>0.00</Amount>
                </ProvisionSummaryItemInfo>
                <ProvisionSummaryItemInfo>
                    <AssetClassificationType>020006</AssetClassificationType>
                    <Amount>0.00</Amount>
                </ProvisionSummaryItemInfo>
            </ProvisionSummaryItem960023>
            <ProvisionSummaryItem960010 name="">
                <ProvisionSummaryItemInfo>
                    <AssetClassificationType>020001</AssetClassificationType>
                    <Amount>0.00</Amount>
                </ProvisionSummaryItemInfo>
                <ProvisionSummaryItemInfo>
                    <AssetClassificationType>020002</AssetClassificationType>
                    <Amount>0.00</Amount>
                </ProvisionSummaryItemInfo>
                <ProvisionSummaryItemInfo>
                    <AssetClassificationType>020003</AssetClassificationType>
                    <Amount>0.00</Amount>
                </ProvisionSummaryItemInfo>
                <ProvisionSummaryItemInfo>
                    <AssetClassificationType>020004</AssetClassificationType>
                    <Amount>0.00</Amount>
                </ProvisionSummaryItemInfo>
                <ProvisionSummaryItemInfo>
                    <AssetClassificationType>020005</AssetClassificationType>
                    <Amount>218777863.14</Amount>
                </ProvisionSummaryItemInfo>
                <ProvisionSummaryItemInfo>
                    <AssetClassificationType>020006</AssetClassificationType>
                    <Amount>0.00</Amount>
                </ProvisionSummaryItemInfo>
            </ProvisionSummaryItem960010>
            <ProvisionSummaryItem960011 name="">
                <ProvisionSummaryItemInfo>
                    <AssetClassificationType>020001</AssetClassificationType>
                    <Amount>0.00</Amount>
                </ProvisionSummaryItemInfo>
                <ProvisionSummaryItemInfo>
                    <AssetClassificationType>020002</AssetClassificationType>
                    <Amount>0.00</Amount>
                </ProvisionSummaryItemInfo>
                <ProvisionSummaryItemInfo>
                    <AssetClassificationType>020003</AssetClassificationType>
                    <Amount>0.00</Amount>
                </ProvisionSummaryItemInfo>
                <ProvisionSummaryItemInfo>
                    <AssetClassificationType>020004</AssetClassificationType>
                    <Amount>0.00</Amount>
                </ProvisionSummaryItemInfo>
                <ProvisionSummaryItemInfo>
                    <AssetClassificationType>020005</AssetClassificationType>
                    <Amount>0.00</Amount>
                </ProvisionSummaryItemInfo>
                <ProvisionSummaryItemInfo>
                    <AssetClassificationType>020006</AssetClassificationType>
                    <Amount>0.00</Amount>
                </ProvisionSummaryItemInfo>
            </ProvisionSummaryItem960011>
            <ProvisionSummaryItem960025 name="">
                <ProvisionSummaryItemInfo>
                    <AssetClassificationType>020001</AssetClassificationType>
                    <Amount>0.00</Amount>
                </ProvisionSummaryItemInfo>
                <ProvisionSummaryItemInfo>
                    <AssetClassificationType>020002</AssetClassificationType>
                    <Amount>0.00</Amount>
                </ProvisionSummaryItemInfo>
                <ProvisionSummaryItemInfo>
                    <AssetClassificationType>020003</AssetClassificationType>
                    <Amount>0.00</Amount>
                </ProvisionSummaryItemInfo>
                <ProvisionSummaryItemInfo>
                    <AssetClassificationType>020004</AssetClassificationType>
                    <Amount>0.00</Amount>
                </ProvisionSummaryItemInfo>
                <ProvisionSummaryItemInfo>
                    <AssetClassificationType>020005</AssetClassificationType>
                    <Amount>0.00</Amount>
                </ProvisionSummaryItemInfo>
                <ProvisionSummaryItemInfo>
                    <AssetClassificationType>020006</AssetClassificationType>
                    <Amount>0.00</Amount>
                </ProvisionSummaryItemInfo>
            </ProvisionSummaryItem960025>
            <ProvisionSummaryItem960026 name="">
                <ProvisionSummaryItemInfo>
                    <AssetClassificationType>020001</AssetClassificationType>
                    <Amount>307564426.99</Amount>
                </ProvisionSummaryItemInfo>
                <ProvisionSummaryItemInfo>
                    <AssetClassificationType>020002</AssetClassificationType>
                    <Amount>42259622.56</Amount>
                </ProvisionSummaryItemInfo>
                <ProvisionSummaryItemInfo>
                    <AssetClassificationType>020003</AssetClassificationType>
                    <Amount>455360781.58</Amount>
                </ProvisionSummaryItemInfo>
                <ProvisionSummaryItemInfo>
                    <AssetClassificationType>020004</AssetClassificationType>
                    <Amount>368365084.81</Amount>
                </ProvisionSummaryItemInfo>
                <ProvisionSummaryItemInfo>
                    <AssetClassificationType>020005</AssetClassificationType>
                    <Amount>851473765.14</Amount>
                </ProvisionSummaryItemInfo>
                <ProvisionSummaryItemInfo>
                    <AssetClassificationType>020006</AssetClassificationType>
                    <Amount>0.00</Amount>
                </ProvisionSummaryItemInfo>
            </ProvisionSummaryItem960026>
            <ProvisionSummaryItem960027 name="">
                <ProvisionSummaryItemInfo>
                    <AssetClassificationType>020001</AssetClassificationType>
                    <Amount>0.00</Amount>
                </ProvisionSummaryItemInfo>
                <ProvisionSummaryItemInfo>
                    <AssetClassificationType>020002</AssetClassificationType>
                    <Amount>0.00</Amount>
                </ProvisionSummaryItemInfo>
                <ProvisionSummaryItemInfo>
                    <AssetClassificationType>020003</AssetClassificationType>
                    <Amount>0.00</Amount>
                </ProvisionSummaryItemInfo>
                <ProvisionSummaryItemInfo>
                    <AssetClassificationType>020004</AssetClassificationType>
                    <Amount>0.00</Amount>
                </ProvisionSummaryItemInfo>
                <ProvisionSummaryItemInfo>
                    <AssetClassificationType>020005</AssetClassificationType>
                    <Amount>0.00</Amount>
                </ProvisionSummaryItemInfo>
                <ProvisionSummaryItemInfo>
                    <AssetClassificationType>020006</AssetClassificationType>
                    <Amount>0.00</Amount>
                </ProvisionSummaryItemInfo>
            </ProvisionSummaryItem960027>
            <ProvisionSummaryItem960028 name="">
                <ProvisionSummaryItemInfo>
                    <AssetClassificationType>020001</AssetClassificationType>
                    <Amount>0.00</Amount>
                </ProvisionSummaryItemInfo>
                <ProvisionSummaryItemInfo>
                    <AssetClassificationType>020002</AssetClassificationType>
                    <Amount>0.00</Amount>
                </ProvisionSummaryItemInfo>
                <ProvisionSummaryItemInfo>
                    <AssetClassificationType>020003</AssetClassificationType>
                    <Amount>0.00</Amount>
                </ProvisionSummaryItemInfo>
                <ProvisionSummaryItemInfo>
                    <AssetClassificationType>020004</AssetClassificationType>
                    <Amount>0.00</Amount>
                </ProvisionSummaryItemInfo>
                <ProvisionSummaryItemInfo>
                    <AssetClassificationType>020005</AssetClassificationType>
                    <Amount>0.00</Amount>
                </ProvisionSummaryItemInfo>
                <ProvisionSummaryItemInfo>
                    <AssetClassificationType>020006</AssetClassificationType>
                    <Amount>0.00</Amount>
                </ProvisionSummaryItemInfo>
            </ProvisionSummaryItem960028>
            <ProvisionSummaryItem960014 name="">
                <ProvisionSummaryItemInfo>
                    <AssetClassificationType>020001</AssetClassificationType>
                    <Amount>0.00</Amount>
                </ProvisionSummaryItemInfo>
                <ProvisionSummaryItemInfo>
                    <AssetClassificationType>020002</AssetClassificationType>
                    <Amount>0.00</Amount>
                </ProvisionSummaryItemInfo>
                <ProvisionSummaryItemInfo>
                    <AssetClassificationType>020003</AssetClassificationType>
                    <Amount>0.00</Amount>
                </ProvisionSummaryItemInfo>
                <ProvisionSummaryItemInfo>
                    <AssetClassificationType>020004</AssetClassificationType>
                    <Amount>0.00</Amount>
                </ProvisionSummaryItemInfo>
                <ProvisionSummaryItemInfo>
                    <AssetClassificationType>020005</AssetClassificationType>
                    <Amount>0.00</Amount>
                </ProvisionSummaryItemInfo>
                <ProvisionSummaryItemInfo>
                    <AssetClassificationType>020006</AssetClassificationType>
                    <Amount>0.00</Amount>
                </ProvisionSummaryItemInfo>
            </ProvisionSummaryItem960014>
            <ProvisionSummaryItem960015 name="">
                <ProvisionSummaryItemInfo>
                    <AssetClassificationType>020001</AssetClassificationType>
                    <Amount>0.00</Amount>
                </ProvisionSummaryItemInfo>
                <ProvisionSummaryItemInfo>
                    <AssetClassificationType>020002</AssetClassificationType>
                    <Amount>0.00</Amount>
                </ProvisionSummaryItemInfo>
                <ProvisionSummaryItemInfo>
                    <AssetClassificationType>020003</AssetClassificationType>
                    <Amount>0.00</Amount>
                </ProvisionSummaryItemInfo>
                <ProvisionSummaryItemInfo>
                    <AssetClassificationType>020004</AssetClassificationType>
                    <Amount>0.00</Amount>
                </ProvisionSummaryItemInfo>
                <ProvisionSummaryItemInfo>
                    <AssetClassificationType>020005</AssetClassificationType>
                    <Amount>0.00</Amount>
                </ProvisionSummaryItemInfo>
                <ProvisionSummaryItemInfo>
                    <AssetClassificationType>020006</AssetClassificationType>
                    <Amount>0.00</Amount>
                </ProvisionSummaryItemInfo>
            </ProvisionSummaryItem960015>
            <ProvisionSummaryItem960016 name="">
                <ProvisionSummaryItemInfo>
                    <AssetClassificationType>020001</AssetClassificationType>
                    <Amount>0.00</Amount>
                </ProvisionSummaryItemInfo>
                <ProvisionSummaryItemInfo>
                    <AssetClassificationType>020002</AssetClassificationType>
                    <Amount>0.00</Amount>
                </ProvisionSummaryItemInfo>
                <ProvisionSummaryItemInfo>
                    <AssetClassificationType>020003</AssetClassificationType>
                    <Amount>0.00</Amount>
                </ProvisionSummaryItemInfo>
                <ProvisionSummaryItemInfo>
                    <AssetClassificationType>020004</AssetClassificationType>
                    <Amount>0.00</Amount>
                </ProvisionSummaryItemInfo>
                <ProvisionSummaryItemInfo>
                    <AssetClassificationType>020005</AssetClassificationType>
                    <Amount>0.00</Amount>
                </ProvisionSummaryItemInfo>
                <ProvisionSummaryItemInfo>
                    <AssetClassificationType>020006</AssetClassificationType>
                    <Amount>0.00</Amount>
                </ProvisionSummaryItemInfo>
            </ProvisionSummaryItem960016>
            <ProvisionSummaryItem960031 name="">
                <ProvisionSummaryItemInfo>
                    <AssetClassificationType>020001</AssetClassificationType>
                    <Amount>0.00</Amount>
                </ProvisionSummaryItemInfo>
                <ProvisionSummaryItemInfo>
                    <AssetClassificationType>020002</AssetClassificationType>
                    <Amount>0.00</Amount>
                </ProvisionSummaryItemInfo>
                <ProvisionSummaryItemInfo>
                    <AssetClassificationType>020003</AssetClassificationType>
                    <Amount>0.00</Amount>
                </ProvisionSummaryItemInfo>
                <ProvisionSummaryItemInfo>
                    <AssetClassificationType>020004</AssetClassificationType>
                    <Amount>0.00</Amount>
                </ProvisionSummaryItemInfo>
                <ProvisionSummaryItemInfo>
                    <AssetClassificationType>020005</AssetClassificationType>
                    <Amount>0.00</Amount>
                </ProvisionSummaryItemInfo>
                <ProvisionSummaryItemInfo>
                    <AssetClassificationType>020006</AssetClassificationType>
                    <Amount>0.00</Amount>
                </ProvisionSummaryItemInfo>
            </ProvisionSummaryItem960031>
            <ProvisionSummaryItem960032 name="">
                <ProvisionSummaryItemInfo>
                    <AssetClassificationType>020001</AssetClassificationType>
                    <Amount>307564426.99</Amount>
                </ProvisionSummaryItemInfo>
                <ProvisionSummaryItemInfo>
                    <AssetClassificationType>020002</AssetClassificationType>
                    <Amount>42259622.56</Amount>
                </ProvisionSummaryItemInfo>
                <ProvisionSummaryItemInfo>
                    <AssetClassificationType>020003</AssetClassificationType>
                    <Amount>455360781.58</Amount>
                </ProvisionSummaryItemInfo>
                <ProvisionSummaryItemInfo>
                    <AssetClassificationType>020004</AssetClassificationType>
                    <Amount>368365084.81</Amount>
                </ProvisionSummaryItemInfo>
                <ProvisionSummaryItemInfo>
                    <AssetClassificationType>020005</AssetClassificationType>
                    <Amount>851473765.14</Amount>
                </ProvisionSummaryItemInfo>
                <ProvisionSummaryItemInfo>
                    <AssetClassificationType>020006</AssetClassificationType>
                    <Amount>0.00</Amount>
                </ProvisionSummaryItemInfo>
            </ProvisionSummaryItem960032>
            <ProvisionSummaryItem960033 name="">
                <ProvisionSummaryItemInfo>
                    <AssetClassificationType>020001</AssetClassificationType>
                    <Amount>0.00</Amount>
                </ProvisionSummaryItemInfo>
                <ProvisionSummaryItemInfo>
                    <AssetClassificationType>020002</AssetClassificationType>
                    <Amount>0.00</Amount>
                </ProvisionSummaryItemInfo>
                <ProvisionSummaryItemInfo>
                    <AssetClassificationType>020003</AssetClassificationType>
                    <Amount>0.00</Amount>
                </ProvisionSummaryItemInfo>
                <ProvisionSummaryItemInfo>
                    <AssetClassificationType>020004</AssetClassificationType>
                    <Amount>0.00</Amount>
                </ProvisionSummaryItemInfo>
                <ProvisionSummaryItemInfo>
                    <AssetClassificationType>020005</AssetClassificationType>
                    <Amount>0.00</Amount>
                </ProvisionSummaryItemInfo>
                <ProvisionSummaryItemInfo>
                    <AssetClassificationType>020006</AssetClassificationType>
                    <Amount>0.00</Amount>
                </ProvisionSummaryItemInfo>
            </ProvisionSummaryItem960033>
            <ProvisionSummaryItem960034 name="">
                <ProvisionSummaryItemInfo>
                    <AssetClassificationType>020001</AssetClassificationType>
                    <Amount>0.00</Amount>
                </ProvisionSummaryItemInfo>
                <ProvisionSummaryItemInfo>
                    <AssetClassificationType>020002</AssetClassificationType>
                    <Amount>0.00</Amount>
                </ProvisionSummaryItemInfo>
                <ProvisionSummaryItemInfo>
                    <AssetClassificationType>020003</AssetClassificationType>
                    <Amount>0.00</Amount>
                </ProvisionSummaryItemInfo>
                <ProvisionSummaryItemInfo>
                    <AssetClassificationType>020004</AssetClassificationType>
                    <Amount>0.00</Amount>
                </ProvisionSummaryItemInfo>
                <ProvisionSummaryItemInfo>
                    <AssetClassificationType>020005</AssetClassificationType>
                    <Amount>0.00</Amount>
                </ProvisionSummaryItemInfo>
                <ProvisionSummaryItemInfo>
                    <AssetClassificationType>020006</AssetClassificationType>
                    <Amount>0.00</Amount>
                </ProvisionSummaryItemInfo>
            </ProvisionSummaryItem960034>
            <ProvisionSummaryItem960035 name="">
                <ProvisionSummaryItemInfo>
                    <AssetClassificationType>020001</AssetClassificationType>
                    <Amount>0.00</Amount>
                </ProvisionSummaryItemInfo>
                <ProvisionSummaryItemInfo>
                    <AssetClassificationType>020002</AssetClassificationType>
                    <Amount>0.00</Amount>
                </ProvisionSummaryItemInfo>
                <ProvisionSummaryItemInfo>
                    <AssetClassificationType>020003</AssetClassificationType>
                    <Amount>0.00</Amount>
                </ProvisionSummaryItemInfo>
                <ProvisionSummaryItemInfo>
                    <AssetClassificationType>020004</AssetClassificationType>
                    <Amount>0.00</Amount>
                </ProvisionSummaryItemInfo>
                <ProvisionSummaryItemInfo>
                    <AssetClassificationType>020005</AssetClassificationType>
                    <Amount>0.00</Amount>
                </ProvisionSummaryItemInfo>
                <ProvisionSummaryItemInfo>
                    <AssetClassificationType>020006</AssetClassificationType>
                    <Amount>0.00</Amount>
                </ProvisionSummaryItemInfo>
            </ProvisionSummaryItem960035>
            <ProvisionSummaryItem960036 name="">
                <ProvisionSummaryItemInfo>
                    <AssetClassificationType>020001</AssetClassificationType>
                    <Amount>0.00</Amount>
                </ProvisionSummaryItemInfo>
                <ProvisionSummaryItemInfo>
                    <AssetClassificationType>020002</AssetClassificationType>
                    <Amount>0.00</Amount>
                </ProvisionSummaryItemInfo>
                <ProvisionSummaryItemInfo>
                    <AssetClassificationType>020003</AssetClassificationType>
                    <Amount>0.00</Amount>
                </ProvisionSummaryItemInfo>
                <ProvisionSummaryItemInfo>
                    <AssetClassificationType>020004</AssetClassificationType>
                    <Amount>0.00</Amount>
                </ProvisionSummaryItemInfo>
                <ProvisionSummaryItemInfo>
                    <AssetClassificationType>020005</AssetClassificationType>
                    <Amount>0.00</Amount>
                </ProvisionSummaryItemInfo>
                <ProvisionSummaryItemInfo>
                    <AssetClassificationType>020006</AssetClassificationType>
                    <Amount>0.00</Amount>
                </ProvisionSummaryItemInfo>
            </ProvisionSummaryItem960036>
            <ProvisionSummaryItem960037 name="">
                <ProvisionSummaryItemInfo>
                    <AssetClassificationType>020001</AssetClassificationType>
                    <Amount>0.00</Amount>
                </ProvisionSummaryItemInfo>
                <ProvisionSummaryItemInfo>
                    <AssetClassificationType>020002</AssetClassificationType>
                    <Amount>0.00</Amount>
                </ProvisionSummaryItemInfo>
                <ProvisionSummaryItemInfo>
                    <AssetClassificationType>020003</AssetClassificationType>
                    <Amount>0.00</Amount>
                </ProvisionSummaryItemInfo>
                <ProvisionSummaryItemInfo>
                    <AssetClassificationType>020004</AssetClassificationType>
                    <Amount>0.00</Amount>
                </ProvisionSummaryItemInfo>
                <ProvisionSummaryItemInfo>
                    <AssetClassificationType>020005</AssetClassificationType>
                    <Amount>0.00</Amount>
                </ProvisionSummaryItemInfo>
                <ProvisionSummaryItemInfo>
                    <AssetClassificationType>020006</AssetClassificationType>
                    <Amount>0.00</Amount>
                </ProvisionSummaryItemInfo>
            </ProvisionSummaryItem960037>
        </ContentRecordGroup>
    </DS_PVS_Content>
</DS_PVS>